// Full Pokémon Pokopia dataset merged from Serebii + Google Sheets
// Each entry has: id, name, number, type, specialty, location, idealHabitat, favourites[], flavor, imageUrl, serebiiUrl
// dataSource: "both" | "serebii_only" | "sheet_only"

const RAW_POKEMON = [
  { id: 1, name: "Bulbasaur", number: "001", type: "Grass/Poison", specialty: ["Grow"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Nature","Soft stuff","Cute stuff","Water","Group activities"], flavor: "Sweet" },
  { id: 2, name: "Ivysaur", number: "002", type: "Grass/Poison", specialty: ["Grow"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Nature","Soft stuff","Cute stuff","Pretty flowers","Group activities"], flavor: "Sour" },
  { id: 3, name: "Venusaur", number: "003", type: "Grass/Poison", specialty: ["Grow","Litter"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Nature","Soft stuff","Cute stuff","Pretty flowers","Luxury"], flavor: "Sour" },
  { id: 4, name: "Charmander", number: "004", type: "Fire", specialty: ["Burn"], location: "Withered Wasteland", idealHabitat: "Warm", favourites: ["Fire","Wooden stuff","Hard stuff","Exercise","Group activities"], flavor: "Spicy" },
  { id: 5, name: "Charmeleon", number: "005", type: "Fire", specialty: ["Burn"], location: "Withered Wasteland", idealHabitat: "Warm", favourites: ["Fire","Wooden stuff","Hard stuff","Exercise","Rides"], flavor: "Spicy" },
  { id: 6, name: "Charizard", number: "006", type: "Fire/Flying", specialty: ["Burn","Fly"], location: "Withered Wasteland", idealHabitat: "Warm", favourites: ["Fire","Nice breezes","Wooden stuff","Exercise","Luxury"], flavor: "Spicy" },
  { id: 7, name: "Squirtle", number: "007", type: "Water", specialty: ["Water"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Water","Cleanliness","Healing","Cute stuff","Group activities"], flavor: "Sweet" },
  { id: 8, name: "Wartortle", number: "008", type: "Water", specialty: ["Water"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Water","Cleanliness","Healing","Exercise","Hard stuff"], flavor: "Spicy" },
  { id: 9, name: "Blastoise", number: "009", type: "Water", specialty: ["Water","Trade"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Water","Cleanliness","Healing","Exercise","Luxury"], flavor: "Sour" },
  { id: 10, name: "Pidgey", number: "016", type: "Normal/Flying", specialty: ["Fly","Search"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Soft stuff","Nice breezes","Watching stuff","Nature","Play spaces"], flavor: "Sour" },
  { id: 11, name: "Pidgeotto", number: "017", type: "Normal/Flying", specialty: ["Fly","Search"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Soft stuff","Nice breezes","Watching stuff","Nature","Looks like food"], flavor: "Spicy" },
  { id: 12, name: "Pidgeot", number: "018", type: "Normal/Flying", specialty: ["Chop","Fly"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Soft stuff","Nice breezes","Wooden stuff","Nature","Luxury"], flavor: "Sour" },
  { id: 13, name: "Oddish", number: "043", type: "Grass/Poison", specialty: ["Grow"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Nature","Dirt","Soft stuff","Pretty flowers","Water"], flavor: "Bitter" },
  { id: 14, name: "Gloom", number: "044", type: "Grass/Poison", specialty: ["Grow"], location: "Bleak Beach", idealHabitat: "Humid", favourites: ["Nature","Dirt","Soft stuff","Pretty flowers","Garbage"], flavor: "Dry" },
  { id: 15, name: "Vileplume", number: "045", type: "Grass/Poison", specialty: ["Grow","Litter"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Nature","Dirt","Soft stuff","Pretty flowers","Colourful stuff"], flavor: "Bitter" },
  { id: 16, name: "Bellossom", number: "182", type: "Grass", specialty: ["Grow","Hype"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Nature","Pretty flowers","Play spaces","Cute stuff","Noisy stuff"], flavor: "Sour" },
  { id: 17, name: "Paras", number: "046", type: "Bug/Grass", specialty: ["Search"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Nature","Wooden stuff","Watching stuff","Dirt","Looks like food"], flavor: "Bitter" },
  { id: 18, name: "Parasect", number: "047", type: "Bug/Grass", specialty: ["Search"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Nature","Wooden stuff","Watching stuff","Dirt","Strange stuff"], flavor: "Bitter" },
  { id: 19, name: "Venonat", number: "048", type: "Bug/Poison", specialty: ["Search"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Nature","Wooden stuff","Watching stuff","Complicated stuff","Letters/words"], flavor: "Bitter" },
  { id: 20, name: "Venomoth", number: "049", type: "Bug/Poison", specialty: ["Search"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Nature","Wooden stuff","Watching stuff","Nice Breezes","Pretty flowers"], flavor: "Bitter" },
  { id: 21, name: "Bellsprout", number: "069", type: "Grass/Poison", specialty: ["Grow","Litter"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Nature","Wooden stuff","Dirt","Water","Pretty flowers"], flavor: "Dry" },
  { id: 22, name: "Weepinbell", number: "070", type: "Grass/Poison", specialty: ["Grow","Litter"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Nature","Wooden stuff","Dirt","Colourful stuff","Pretty flowers"], flavor: "Bitter" },
  { id: 23, name: "Victreebel", number: "071", type: "Grass/Poison", specialty: ["Grow","Chop"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Nature","Wooden stuff","Dirt","Colourful stuff","Pretty flowers"], flavor: "Bitter" },
  { id: 24, name: "Slowpoke", number: "079", type: "Water/Psychic", specialty: ["Water","Yawn"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Water","Cleanliness","Strange stuff","Soft stuff","Healing"], flavor: "Dry" },
  { id: 25, name: "Slowbro", number: "080", type: "Water/Psychic", specialty: ["Water","Trade"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Water","Cleanliness","Strange stuff","Group activities","Healing"], flavor: "Dry" },
  { id: 26, name: "Slowking", number: "199", type: "Water/Psychic", specialty: ["Water","Teleport"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Water","Cleanliness","Strange stuff","Group activities","Healing"], flavor: "Sour" },
  { id: 27, name: "Magnemite", number: "081", type: "Electric/Steel", specialty: ["Generate"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Electronics","Metal stuff","Shiny stuff","Hard stuff","Group activities"], flavor: "Bitter" },
  { id: 28, name: "Magneton", number: "082", type: "Electric/Steel", specialty: ["Generate"], location: "Bleak Beach", idealHabitat: "Bright", favourites: ["Electronics","Metal stuff","Shiny stuff","Gatherings","Group activities"], flavor: "Bitter" },
  { id: 29, name: "Magnezone", number: "462", type: "Electric/Steel", specialty: ["Generate","Recycle"], location: "Bleak Beach", idealHabitat: "Bright", favourites: ["Electronics","Metal stuff","Luxury","Gatherings","Hard stuff"], flavor: "Bitter" },
  { id: 30, name: "Onix", number: "095", type: "Rock/Ground", specialty: ["Crush","Bull"], location: "Withered Wasteland", idealHabitat: "Dry", favourites: ["Stone stuff","Dirt","Blocky stuff","Slender objects","Exercise"], flavor: "Dry" },
  { id: 31, name: "Steelix", number: "208", type: "Steel/Ground", specialty: ["Crush","Bull"], location: "Rocky Ridges", idealHabitat: "Dry", favourites: ["Metal stuff","Dirt","Stone stuff","Slender objects","Hard stuff"], flavor: "Sour" },
  { id: 32, name: "Cubone", number: "104", type: "Ground", specialty: ["Build"], location: "Withered Wasteland", idealHabitat: "Dry", favourites: ["Dirt","Construction","Exercise","Slender objects","Group activities"], flavor: "Bitter" },
  { id: 33, name: "Marowak", number: "105", type: "Ground", specialty: ["Build"], location: "Withered Wasteland", idealHabitat: "Dry", favourites: ["Dirt","Construction","Exercise","Slender objects","Luxury"], flavor: "Dry" },
  { id: 34, name: "Tyrogue", number: "236", type: "Fighting", specialty: ["Trade"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Exercise","Group activities","Fabric","Stone stuff","Round stuff"], flavor: "Spicy" },
  { id: 35, name: "Hitmonlee", number: "106", type: "Fighting", specialty: ["Trade"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Exercise","Group activities","Fabric","Stone stuff","Round stuff"], flavor: "Spicy" },
  { id: 36, name: "Hitmonchan", number: "107", type: "Fighting", specialty: ["Trade"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Exercise","Group activities","Fabric","Stone stuff","Round stuff"], flavor: "Sweet" },
  { id: 37, name: "Hitmontop", number: "237", type: "Fighting", specialty: ["Trade"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Exercise","Group activities","Fabric","Stone stuff","Round stuff"], flavor: "Sweet" },
  { id: 38, name: "Koffing", number: "109", type: "Poison", specialty: ["Recycle"], location: "Palette Town", idealHabitat: "Dark", favourites: ["Garbage","Gatherings","Complicated stuff","Soft stuff","Wobbly stuff"], flavor: "Bitter" },
  { id: 39, name: "Weezing", number: "110", type: "Poison", specialty: ["Recycle"], location: "Palette Town", idealHabitat: "Dark", favourites: ["Garbage","Gatherings","Complicated stuff","Soft stuff","Wobbly stuff"], flavor: "Bitter" },
  { id: 40, name: "Tangela", number: "114", type: "Grass", specialty: ["Grow","Litter"], location: "Palette Town", idealHabitat: "Humid", favourites: ["Nature","Water","Gatherings","Pretty flowers","Slender objects"], flavor: "Sour" },
  { id: 41, name: "Tangrowth", number: "465", type: "Grass", specialty: ["Appraise"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Nature","Complicated stuff","Letters/words","Strange stuff","Group activities"], flavor: "Dry" },
  { id: 42, name: "Scyther", number: "123", type: "Bug/Flying", specialty: ["Chop"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Nature","Nice breezes","Wooden stuff","Sharp stuff","Exercise"], flavor: "Spicy" },
  { id: 43, name: "Scizor", number: "212", type: "Bug/Steel", specialty: ["Chop"], location: "Palette Town", idealHabitat: "Bright", favourites: ["Nature","Metal stuff","Wooden stuff","Hard stuff","Exercise"], flavor: "Bitter" },
  { id: 44, name: "Pinsir", number: "127", type: "Bug", specialty: ["Chop","Build"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Nature","Wooden stuff","Pretty flowers","Sharp stuff","Exercise"], flavor: "Spicy" },
  { id: 45, name: "Magikarp", number: "129", type: "Water", specialty: ["???"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Water","Ocean vibes","Group activities","Rides","Wobbly stuff"], flavor: "Sweet" },
  { id: 46, name: "Gyarados", number: "130", type: "Water/Flying", specialty: ["Water"], location: "Sparkling Skylands", idealHabitat: "Humid", favourites: ["Water","Ocean vibes","Nice breezes","Cleanliness","Slender objects"], flavor: "Spicy" },
  { id: 47, name: "Ditto", number: "132", type: "Normal", specialty: ["Transform"], location: "Any", idealHabitat: "Bright", favourites: [], flavor: "Neutral" },
  { id: 48, name: "Hoothoot", number: "163", type: "Normal/Flying", specialty: ["Trade","Fly"], location: "Withered Wasteland", idealHabitat: "Dark", favourites: ["Soft stuff","Nice breezes","Fabric","Wobbly stuff","Watching stuff"], flavor: "Dry" },
  { id: 49, name: "Noctowl", number: "164", type: "Normal/Flying", specialty: ["Trade","Fly"], location: "Withered Wasteland", idealHabitat: "Dark", favourites: ["Soft stuff","Nice breezes","Letters/words","Containers","Watching stuff"], flavor: "Dry" },
  { id: 50, name: "Heracross", number: "214", type: "Bug/Fighting", specialty: ["Chop","Build"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Nature","Wooden stuff","Pretty flowers","Looks like food","Exercise"], flavor: "Sweet" },
  { id: 51, name: "Volbeat", number: "313", type: "Bug", specialty: ["Hype"], location: "Withered Wasteland", idealHabitat: "Dark", favourites: ["Nature","Wooden stuff","Shiny stuff","Cute stuff","Group activities"], flavor: "Sweet" },
  { id: 52, name: "Illumise", number: "314", type: "Bug", specialty: ["Hype"], location: "Withered Wasteland", idealHabitat: "Dark", favourites: ["Nature","Wooden stuff","Shiny stuff","Cute stuff","Group activities"], flavor: "Sour" },
  { id: 53, name: "Surskit", number: "283", type: "Bug/Water", specialty: ["Search"], location: "Bleak Beach", idealHabitat: "Humid", favourites: ["Nature","Water","Cute stuff","Cleanliness","Play spaces"], flavor: "Sweet" },
  { id: 54, name: "Masquerain", number: "284", type: "Bug/Flying", specialty: ["Search"], location: "Bleak Beach", idealHabitat: "Humid", favourites: ["Nature","Water","Pretty flowers","Nice breezes","Watching stuff"], flavor: "Bitter" },
  { id: 55, name: "Nincada", number: "290", type: "Bug/Ground", specialty: ["Search"], location: "Withered Wasteland", idealHabitat: "Dry", favourites: ["Nature","Dirt","Watching stuff","Wooden stuff","Hard stuff"], flavor: "Bitter" },
  { id: 56, name: "Ninjask", number: "291", type: "Bug/Flying", specialty: ["Search"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Nature","Nice breezes","Watching stuff","Shiny stuff","Exercise"], flavor: "Spicy" },
  { id: 57, name: "Shedinja", number: "292", type: "Bug/Ghost", specialty: ["Search"], location: "Withered Wasteland", idealHabitat: "Dark", favourites: ["Nature","Strange stuff","Watching stuff","Wooden stuff","Complicated stuff"], flavor: "Bitter" },
  { id: 58, name: "Roselia", number: "315", type: "Grass/Poison", specialty: ["Grow"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Nature","Pretty flowers","Cute stuff","Colourful stuff","Healing"], flavor: "Bitter" },
  { id: 59, name: "Roserade", number: "407", type: "Grass/Poison", specialty: ["Grow","Hype"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Nature","Pretty flowers","Colourful stuff","Sharp stuff","Luxury"], flavor: "Bitter" },
  { id: 60, name: "Wailmer", number: "320", type: "Water", specialty: ["Water"], location: "Bleak Beach", idealHabitat: "Humid", favourites: ["Water","Ocean vibes","Group activities","Round stuff","Noisy stuff"], flavor: "Sweet" },
  { id: 61, name: "Wailord", number: "321", type: "Water", specialty: ["Water","Bull"], location: "Bleak Beach", idealHabitat: "Humid", favourites: ["Water","Ocean vibes","Group activities","Rides","Luxury"], flavor: "Sweet" },
  { id: 62, name: "Torkoal", number: "324", type: "Fire", specialty: ["Burn"], location: "Rocky Ridges", idealHabitat: "Warm", favourites: ["Fire","Stone stuff","Healing","Hard stuff","Soft stuff"], flavor: "Spicy" },
  { id: 63, name: "Trapinch", number: "328", type: "Ground", specialty: ["Crush"], location: "Withered Wasteland", idealHabitat: "Dry", favourites: ["Dirt","Stone stuff","Watching stuff","Round stuff","Hard stuff"], flavor: "Bitter" },
  { id: 64, name: "Vibrava", number: "329", type: "Ground/Dragon", specialty: ["Crush"], location: "Withered Wasteland", idealHabitat: "Dry", favourites: ["Dirt","Stone stuff","Nice breezes","Noisy stuff","Colourful stuff"], flavor: "Sour" },
  { id: 65, name: "Flygon", number: "330", type: "Ground/Dragon", specialty: ["Crush","Fly"], location: "Withered Wasteland", idealHabitat: "Dry", favourites: ["Dirt","Stone stuff","Nice breezes","Noisy stuff","Luxury"], flavor: "Sour" },
  { id: 66, name: "Cacnea", number: "331", type: "Grass", specialty: ["Grow"], location: "Withered Wasteland", idealHabitat: "Dry", favourites: ["Nature","Dirt","Exercise","Hard stuff","Group activities"], flavor: "Bitter" },
  { id: 67, name: "Cacturne", number: "332", type: "Grass/Dark", specialty: ["Grow"], location: "Withered Wasteland", idealHabitat: "Dark", favourites: ["Nature","Dirt","Exercise","Sharp stuff","Strange stuff"], flavor: "Bitter" },
  { id: 68, name: "Barboach", number: "339", type: "Water/Ground", specialty: ["Water"], location: "Rocky Ridges", idealHabitat: "Humid", favourites: ["Water","Dirt","Slender objects","Wobbly stuff","Cleanliness"], flavor: "Dry" },
  { id: 69, name: "Whiscash", number: "340", type: "Water/Ground", specialty: ["Water","Crush"], location: "Rocky Ridges", idealHabitat: "Humid", favourites: ["Water","Dirt","Nature","Wobbly stuff","Luxury"], flavor: "Dry" },
  { id: 70, name: "Corphish", number: "341", type: "Water", specialty: ["Water"], location: "Bleak Beach", idealHabitat: "Humid", favourites: ["Water","Hard stuff","Exercise","Looks like food","Sharp stuff"], flavor: "Spicy" },
  { id: 71, name: "Crawdaunt", number: "342", type: "Water/Dark", specialty: ["Water","Chop"], location: "Bleak Beach", idealHabitat: "Humid", favourites: ["Water","Hard stuff","Exercise","Sharp stuff","Luxury"], flavor: "Spicy" },
  { id: 72, name: "Feebas", number: "349", type: "Water", specialty: ["???"], location: "Bleak Beach", idealHabitat: "Humid", favourites: ["Water","Cleanliness","Cute stuff","Ocean vibes","Group activities"], flavor: "Dry" },
  { id: 73, name: "Milotic", number: "350", type: "Water", specialty: ["Water","Hype"], location: "Sparkling Skylands", idealHabitat: "Humid", favourites: ["Water","Cleanliness","Pretty flowers","Healing","Luxury"], flavor: "Sweet" },
  { id: 74, name: "Kecleon", number: "352", type: "Normal", specialty: ["Trade"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Colourful stuff","Nature","Watching stuff","Cute stuff","Complicated stuff"], flavor: "Sour" },
  { id: 75, name: "Tropius", number: "357", type: "Grass/Flying", specialty: ["Grow","Fly"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Nature","Nice breezes","Looks like food","Pretty flowers","Rides"], flavor: "Sweet" },
  { id: 76, name: "Chimecho", number: "358", type: "Psychic", specialty: ["Hype"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Noisy stuff","Nice breezes","Healing","Shiny stuff","Cute stuff"], flavor: "Dry" },
  { id: 77, name: "Turtwig", number: "387", type: "Grass", specialty: ["Grow"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Nature","Dirt","Soft stuff","Pretty flowers","Group activities"], flavor: "Bitter" },
  { id: 78, name: "Grotle", number: "388", type: "Grass", specialty: ["Grow"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Nature","Dirt","Soft stuff","Pretty flowers","Looks like food"], flavor: "Bitter" },
  { id: 79, name: "Torterra", number: "389", type: "Grass/Ground", specialty: ["Grow","Bull"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Nature","Dirt","Stone stuff","Pretty flowers","Luxury"], flavor: "Sour" },
  { id: 80, name: "Chimchar", number: "390", type: "Fire", specialty: ["Burn"], location: "Rocky Ridges", idealHabitat: "Warm", favourites: ["Fire","Exercise","Play spaces","Looks like food","Group activities"], flavor: "Spicy" },
  { id: 81, name: "Monferno", number: "391", type: "Fire/Fighting", specialty: ["Burn"], location: "Rocky Ridges", idealHabitat: "Warm", favourites: ["Fire","Exercise","Play spaces","Looks like food","Hard stuff"], flavor: "Spicy" },
  { id: 82, name: "Infernape", number: "392", type: "Fire/Fighting", specialty: ["Burn","Build"], location: "Rocky Ridges", idealHabitat: "Warm", favourites: ["Fire","Exercise","Construction","Looks like food","Luxury"], flavor: "Spicy" },
  { id: 83, name: "Piplup", number: "393", type: "Water", specialty: ["Water"], location: "Rocky Ridges", idealHabitat: "Humid", favourites: ["Water","Cleanliness","Cute stuff","Ocean vibes","Group activities"], flavor: "Sweet" },
  { id: 84, name: "Prinplup", number: "394", type: "Water", specialty: ["Water"], location: "Rocky Ridges", idealHabitat: "Humid", favourites: ["Water","Cleanliness","Metal stuff","Ocean vibes","Hard stuff"], flavor: "Sour" },
  { id: 85, name: "Empoleon", number: "395", type: "Water/Steel", specialty: ["Water","Trade"], location: "Rocky Ridges", idealHabitat: "Humid", favourites: ["Water","Cleanliness","Metal stuff","Ocean vibes","Luxury"], flavor: "Sour" },
  { id: 86, name: "Bidoof", number: "399", type: "Normal", specialty: ["Build"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Wooden stuff","Water","Construction","Nature","Group activities"], flavor: "Sweet" },
  { id: 87, name: "Bibarel", number: "400", type: "Normal/Water", specialty: ["Build","Water"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Wooden stuff","Water","Construction","Nature","Luxury"], flavor: "Sweet" },
  { id: 88, name: "Kricketot", number: "401", type: "Bug", specialty: ["Hype"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Nature","Noisy stuff","Cute stuff","Play spaces","Group activities"], flavor: "Sweet" },
  { id: 89, name: "Kricketune", number: "402", type: "Bug", specialty: ["Hype"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Nature","Noisy stuff","Cute stuff","Play spaces","Luxury"], flavor: "Sour" },
  { id: 90, name: "Budew", number: "406", type: "Grass/Poison", specialty: ["Grow"], location: "Withered Wasteland", idealHabitat: "Humid", favourites: ["Nature","Pretty flowers","Cute stuff","Water","Healing"], flavor: "Bitter" },
  { id: 91, name: "Pachirisu", number: "417", type: "Electric", specialty: ["Generate"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Electronics","Cute stuff","Shiny stuff","Play spaces","Group activities"], flavor: "Sweet" },
  { id: 92, name: "Drifloon", number: "425", type: "Ghost/Flying", specialty: ["Fly"], location: "Withered Wasteland", idealHabitat: "Dark", favourites: ["Nice breezes","Wobbly stuff","Cute stuff","Colourful stuff","Strange stuff"], flavor: "Sweet" },
  { id: 93, name: "Drifblim", number: "426", type: "Ghost/Flying", specialty: ["Fly"], location: "Withered Wasteland", idealHabitat: "Dark", favourites: ["Nice breezes","Wobbly stuff","Rides","Colourful stuff","Strange stuff"], flavor: "Dry" },
  { id: 94, name: "Buneary", number: "427", type: "Normal", specialty: ["Trade"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Soft stuff","Cute stuff","Play spaces","Fabric","Group activities"], flavor: "Sweet" },
  { id: 95, name: "Lopunny", number: "428", type: "Normal", specialty: ["Trade"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Soft stuff","Cute stuff","Fabric","Pretty flowers","Luxury"], flavor: "Sweet" },
  { id: 96, name: "Chingling", number: "433", type: "Psychic", specialty: ["Hype"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Noisy stuff","Nice breezes","Cute stuff","Shiny stuff","Group activities"], flavor: "Sweet" },
  { id: 97, name: "Bonsly", number: "438", type: "Rock", specialty: ["Trade"], location: "Withered Wasteland", idealHabitat: "Dry", favourites: ["Stone stuff","Nature","Play spaces","Round stuff","Group activities"], flavor: "Dry" },
  { id: 98, name: "Sudowoodo", number: "185", type: "Rock", specialty: ["Trade","Build"], location: "Withered Wasteland", idealHabitat: "Dry", favourites: ["Stone stuff","Nature","Wooden stuff","Round stuff","Luxury"], flavor: "Dry" },
  { id: 99, name: "Happiny", number: "440", type: "Normal", specialty: ["Trade"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Cute stuff","Round stuff","Healing","Soft stuff","Group activities"], flavor: "Sweet" },
  { id: 100, name: "Chansey", number: "113", type: "Normal", specialty: ["Trade"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Cute stuff","Round stuff","Healing","Soft stuff","Group activities"], flavor: "Sweet" },
  { id: 101, name: "Blissey", number: "242", type: "Normal", specialty: ["Trade","Hype"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Cute stuff","Round stuff","Healing","Soft stuff","Luxury"], flavor: "Sweet" },
  { id: 102, name: "Chatot", number: "441", type: "Normal/Flying", specialty: ["Hype","Fly"], location: "Withered Wasteland", idealHabitat: "Bright", favourites: ["Noisy stuff","Nice breezes","Colourful stuff","Watching stuff","Play spaces"], flavor: "Sour" },
  { id: 103, name: "Spiritomb", number: "442", type: "Ghost/Dark", specialty: ["Search"], location: "Palette Town", idealHabitat: "Dark", favourites: ["Strange stuff","Stone stuff","Complicated stuff","Shiny stuff","Gatherings"], flavor: "Bitter" },
  { id: 104, name: "Munchlax", number: "446", type: "Normal", specialty: ["Trade"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Looks like food","Soft stuff","Round stuff","Play spaces","Group activities"], flavor: "Sweet" },
  { id: 105, name: "Snorlax", number: "143", type: "Normal", specialty: ["Trade","Yawn"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Looks like food","Soft stuff","Round stuff","Healing","Luxury"], flavor: "Sweet" },
  { id: 106, name: "Riolu", number: "447", type: "Fighting", specialty: ["Build"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Exercise","Hard stuff","Group activities","Play spaces","Cute stuff"], flavor: "Spicy" },
  { id: 107, name: "Lucario", number: "448", type: "Fighting/Steel", specialty: ["Build","Trade"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Exercise","Hard stuff","Metal stuff","Construction","Luxury"], flavor: "Spicy" },
  { id: 108, name: "Croagunk", number: "453", type: "Poison/Fighting", specialty: ["Trade"], location: "Palette Town", idealHabitat: "Humid", favourites: ["Exercise","Strange stuff","Wobbly stuff","Dirt","Group activities"], flavor: "Bitter" },
  { id: 109, name: "Toxicroak", number: "454", type: "Poison/Fighting", specialty: ["Trade"], location: "Palette Town", idealHabitat: "Humid", favourites: ["Exercise","Strange stuff","Wobbly stuff","Sharp stuff","Luxury"], flavor: "Bitter" },
  { id: 110, name: "Snover", number: "459", type: "Grass/Ice", specialty: ["Grow"], location: "Sparkling Skylands", idealHabitat: "Cold", favourites: ["Nature","Soft stuff","Pretty flowers","Looks like food","Group activities"], flavor: "Bitter" },
  { id: 111, name: "Abomasnow", number: "460", type: "Grass/Ice", specialty: ["Grow","Chop"], location: "Sparkling Skylands", idealHabitat: "Cold", favourites: ["Nature","Soft stuff","Wooden stuff","Looks like food","Luxury"], flavor: "Bitter" },
  { id: 112, name: "Rotom", number: "479", type: "Electric/Ghost", specialty: ["Generate"], location: "Palette Town", idealHabitat: "Bright", favourites: ["Electronics","Strange stuff","Noisy stuff","Shiny stuff","Complicated stuff"], flavor: "Spicy" },
  { id: 113, name: "Petilil", number: "548", type: "Grass", specialty: ["Grow"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Nature","Pretty flowers","Cute stuff","Healing","Play spaces"], flavor: "Bitter" },
  { id: 114, name: "Lilligant", number: "549", type: "Grass", specialty: ["Grow","Hype"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Nature","Pretty flowers","Colourful stuff","Healing","Luxury"], flavor: "Bitter" },
  { id: 115, name: "Dwebble", number: "557", type: "Bug/Rock", specialty: ["Build"], location: "Bleak Beach", idealHabitat: "Dry", favourites: ["Stone stuff","Nature","Construction","Hard stuff","Group activities"], flavor: "Sour" },
  { id: 116, name: "Crustle", number: "558", type: "Bug/Rock", specialty: ["Build"], location: "Bleak Beach", idealHabitat: "Dry", favourites: ["Stone stuff","Nature","Construction","Hard stuff","Luxury"], flavor: "Sour" },
  { id: 117, name: "Emolga", number: "587", type: "Electric/Flying", specialty: ["Generate","Fly"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Electronics","Nice breezes","Cute stuff","Looks like food","Play spaces"], flavor: "Sweet" },
  { id: 118, name: "Foongus", number: "590", type: "Grass/Poison", specialty: ["Grow"], location: "Palette Town", idealHabitat: "Humid", favourites: ["Nature","Dirt","Round stuff","Strange stuff","Watching stuff"], flavor: "Bitter" },
  { id: 119, name: "Amoonguss", number: "591", type: "Grass/Poison", specialty: ["Grow","Yawn"], location: "Palette Town", idealHabitat: "Humid", favourites: ["Nature","Dirt","Round stuff","Strange stuff","Complicated stuff"], flavor: "Bitter" },
  { id: 120, name: "Alomomola", number: "594", type: "Water", specialty: ["Water","Hype"], location: "Bleak Beach", idealHabitat: "Humid", favourites: ["Water","Healing","Cute stuff","Ocean vibes","Group activities"], flavor: "Sweet" },
  { id: 121, name: "Joltik", number: "595", type: "Bug/Electric", specialty: ["Generate"], location: "Palette Town", idealHabitat: "Bright", favourites: ["Electronics","Nature","Cute stuff","Fabric","Group activities"], flavor: "Sour" },
  { id: 122, name: "Galvantula", number: "596", type: "Bug/Electric", specialty: ["Generate"], location: "Palette Town", idealHabitat: "Bright", favourites: ["Electronics","Nature","Fabric","Complicated stuff","Luxury"], flavor: "Sour" },
  { id: 123, name: "Phantump", number: "708", type: "Ghost/Grass", specialty: ["Grow"], location: "Palette Town", idealHabitat: "Dark", favourites: ["Nature","Wooden stuff","Strange stuff","Cute stuff","Group activities"], flavor: "Bitter" },
  { id: 124, name: "Trevenant", number: "709", type: "Ghost/Grass", specialty: ["Grow","Chop"], location: "Palette Town", idealHabitat: "Dark", favourites: ["Nature","Wooden stuff","Strange stuff","Gatherings","Luxury"], flavor: "Bitter" },
  { id: 125, name: "Pumpkaboo", number: "710", type: "Ghost/Grass", specialty: ["Grow"], location: "Palette Town", idealHabitat: "Dark", favourites: ["Nature","Strange stuff","Cute stuff","Looks like food","Colourful stuff"], flavor: "Sweet" },
  { id: 126, name: "Gourgeist", number: "711", type: "Ghost/Grass", specialty: ["Grow","Hype"], location: "Palette Town", idealHabitat: "Dark", favourites: ["Nature","Strange stuff","Noisy stuff","Looks like food","Colourful stuff"], flavor: "Bitter" },
  { id: 127, name: "Pikipek", number: "731", type: "Normal/Flying", specialty: ["Chop","Fly"], location: "Bleak Beach", idealHabitat: "Bright", favourites: ["Nature","Wooden stuff","Noisy stuff","Looks like food","Play spaces"], flavor: "Spicy" },
  { id: 128, name: "Trumbeak", number: "732", type: "Normal/Flying", specialty: ["Chop","Fly"], location: "Bleak Beach", idealHabitat: "Bright", favourites: ["Nature","Wooden stuff","Noisy stuff","Looks like food","Containers"], flavor: "Spicy" },
  { id: 129, name: "Toucannon", number: "733", type: "Normal/Flying", specialty: ["Chop","Fly"], location: "Bleak Beach", idealHabitat: "Bright", favourites: ["Nature","Wooden stuff","Noisy stuff","Looks like food","Luxury"], flavor: "Spicy" },
  { id: 130, name: "Mudbray", number: "749", type: "Ground", specialty: ["Bull"], location: "Bleak Beach", idealHabitat: "Dry", favourites: ["Dirt","Exercise","Hard stuff","Rides","Group activities"], flavor: "Dry" },
  { id: 131, name: "Mudsdale", number: "750", type: "Ground", specialty: ["Bull"], location: "Bleak Beach", idealHabitat: "Dry", favourites: ["Dirt","Exercise","Hard stuff","Rides","Luxury"], flavor: "Dry" },
  { id: 132, name: "Comfey", number: "764", type: "Fairy", specialty: ["Hype"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Pretty flowers","Healing","Cute stuff","Colourful stuff","Group activities"], flavor: "Sweet" },
  { id: 133, name: "Grubbin", number: "736", type: "Bug", specialty: ["Generate"], location: "Bleak Beach", idealHabitat: "Humid", favourites: ["Electronics","Nature","Dirt","Wooden stuff","Group activities"], flavor: "Sour" },
  { id: 134, name: "Charjabug", number: "737", type: "Bug/Electric", specialty: ["Generate"], location: "Bleak Beach", idealHabitat: "Bright", favourites: ["Electronics","Nature","Blocky stuff","Hard stuff","Group activities"], flavor: "Sour" },
  { id: 135, name: "Vikavolt", number: "738", type: "Bug/Electric", specialty: ["Generate","Fly"], location: "Bleak Beach", idealHabitat: "Bright", favourites: ["Electronics","Nature","Nice breezes","Sharp stuff","Luxury"], flavor: "Sour" },
  { id: 136, name: "Applin", number: "840", type: "Grass/Dragon", specialty: ["Grow"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Nature","Looks like food","Cute stuff","Round stuff","Group activities"], flavor: "Sour" },
  { id: 137, name: "Flapple", number: "841", type: "Grass/Dragon", specialty: ["Grow","Fly"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Nature","Looks like food","Nice breezes","Sharp stuff","Exercise"], flavor: "Sour" },
  { id: 138, name: "Appletun", number: "842", type: "Grass/Dragon", specialty: ["Grow","Yawn"], location: "Rocky Ridges", idealHabitat: "Bright", favourites: ["Nature","Looks like food","Soft stuff","Healing","Luxury"], flavor: "Sweet" },
  { id: 139, name: "Clobbopus", number: "852", type: "Fighting", specialty: ["Build"], location: "Bleak Beach", idealHabitat: "Humid", favourites: ["Exercise","Water","Hard stuff","Group activities","Cute stuff"], flavor: "Spicy" },
  { id: 140, name: "Grapploct", number: "853", type: "Fighting", specialty: ["Build"], location: "Bleak Beach", idealHabitat: "Humid", favourites: ["Exercise","Water","Hard stuff","Slender objects","Luxury"], flavor: "Spicy" },
  { id: 141, name: "Milcery", number: "868", type: "Fairy", specialty: ["Trade"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Cute stuff","Looks like food","Pretty flowers","Soft stuff","Group activities"], flavor: "Sweet" },
  { id: 142, name: "Alcremie", number: "869", type: "Fairy", specialty: ["Trade"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Cute stuff","Looks like food","Pretty flowers","Colourful stuff","Luxury"], flavor: "Sweet" },
  { id: 143, name: "Falinks", number: "870", type: "Fighting", specialty: ["Build"], location: "Bleak Beach", idealHabitat: "Bright", favourites: ["Exercise","Group activities","Hard stuff","Construction","Gatherings"], flavor: "Spicy" },
  { id: 144, name: "Pincurchin", number: "871", type: "Electric", specialty: ["Generate"], location: "Bleak Beach", idealHabitat: "Humid", favourites: ["Electronics","Water","Sharp stuff","Round stuff","Hard stuff"], flavor: "Bitter" },
  { id: 145, name: "Snom", number: "872", type: "Ice/Bug", specialty: ["Search"], location: "Sparkling Skylands", idealHabitat: "Cold", favourites: ["Soft stuff","Cute stuff","Nature","Fabric","Group activities"], flavor: "Sweet" },
  { id: 146, name: "Frosmoth", number: "873", type: "Ice/Bug", specialty: ["Search"], location: "Sparkling Skylands", idealHabitat: "Cold", favourites: ["Soft stuff","Pretty flowers","Nature","Nice breezes","Luxury"], flavor: "Bitter" },
  { id: 147, name: "Dracozolt", number: "880", type: "Electric/Dragon", specialty: ["Generate"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Electronics","Exercise","Noisy stuff","Looks like food","Group activities"], flavor: "Spicy" },
  { id: 148, name: "Arctozolt", number: "881", type: "Electric/Ice", specialty: ["Generate"], location: "Sparkling Skylands", idealHabitat: "Cold", favourites: ["Electronics","Soft stuff","Noisy stuff","Wobbly stuff","Group activities"], flavor: "Bitter" },
  { id: 149, name: "Dracovish", number: "882", type: "Water/Dragon", specialty: ["Water"], location: "Sparkling Skylands", idealHabitat: "Humid", favourites: ["Water","Exercise","Ocean vibes","Looks like food","Group activities"], flavor: "Spicy" },
  { id: 150, name: "Arctovish", number: "883", type: "Water/Ice", specialty: ["Water"], location: "Sparkling Skylands", idealHabitat: "Cold", favourites: ["Water","Soft stuff","Ocean vibes","Cleanliness","Group activities"], flavor: "Bitter" },
  { id: 151, name: "Sprigatito", number: "906", type: "Grass", specialty: ["Grow"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Nature","Cute stuff","Soft stuff","Pretty flowers","Play spaces"], flavor: "Sweet" },
  { id: 152, name: "Floragato", number: "907", type: "Grass", specialty: ["Grow"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Nature","Cute stuff","Pretty flowers","Play spaces","Fabric"], flavor: "Bitter" },
  { id: 153, name: "Meowscarada", number: "908", type: "Grass/Dark", specialty: ["Grow","Hype"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Nature","Pretty flowers","Colourful stuff","Fabric","Luxury"], flavor: "Bitter" },
  { id: 154, name: "Fuecoco", number: "909", type: "Fire", specialty: ["Burn"], location: "Sparkling Skylands", idealHabitat: "Warm", favourites: ["Fire","Looks like food","Cute stuff","Noisy stuff","Group activities"], flavor: "Spicy" },
  { id: 155, name: "Crocalor", number: "910", type: "Fire", specialty: ["Burn"], location: "Sparkling Skylands", idealHabitat: "Warm", favourites: ["Fire","Looks like food","Noisy stuff","Round stuff","Colourful stuff"], flavor: "Spicy" },
  { id: 156, name: "Skeledirge", number: "911", type: "Fire/Ghost", specialty: ["Burn","Hype"], location: "Sparkling Skylands", idealHabitat: "Warm", favourites: ["Fire","Noisy stuff","Strange stuff","Colourful stuff","Luxury"], flavor: "Spicy" },
  { id: 157, name: "Quaxly", number: "912", type: "Water", specialty: ["Water"], location: "Sparkling Skylands", idealHabitat: "Humid", favourites: ["Water","Cleanliness","Cute stuff","Play spaces","Group activities"], flavor: "Sweet" },
  { id: 158, name: "Quaxwell", number: "913", type: "Water", specialty: ["Water"], location: "Sparkling Skylands", idealHabitat: "Humid", favourites: ["Water","Cleanliness","Exercise","Play spaces","Fabric"], flavor: "Sour" },
  { id: 159, name: "Quaquaval", number: "914", type: "Water/Fighting", specialty: ["Water","Hype"], location: "Sparkling Skylands", idealHabitat: "Humid", favourites: ["Water","Cleanliness","Exercise","Colourful stuff","Luxury"], flavor: "Spicy" },
  { id: 160, name: "Smoliv", number: "928", type: "Grass/Normal", specialty: ["Grow"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Nature","Looks like food","Cute stuff","Soft stuff","Group activities"], flavor: "Bitter" },
  { id: 161, name: "Dolliv", number: "929", type: "Grass/Normal", specialty: ["Grow"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Nature","Looks like food","Cute stuff","Pretty flowers","Letters/words"], flavor: "Bitter" },
  { id: 162, name: "Arboliva", number: "930", type: "Grass/Normal", specialty: ["Grow","Hype"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Nature","Looks like food","Pretty flowers","Healing","Luxury"], flavor: "Sour" },
  { id: 163, name: "Squawkabilly", number: "931", type: "Normal/Flying", specialty: ["Fly"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Noisy stuff","Nice breezes","Colourful stuff","Looks like food","Play spaces"], flavor: "Spicy" },
  { id: 164, name: "Nacli", number: "932", type: "Rock", specialty: ["Build"], location: "Sparkling Skylands", idealHabitat: "Dry", favourites: ["Stone stuff","Blocky stuff","Hard stuff","Looks like food","Group activities"], flavor: "Sour" },
  { id: 165, name: "Naclstack", number: "933", type: "Rock", specialty: ["Build"], location: "Sparkling Skylands", idealHabitat: "Dry", favourites: ["Stone stuff","Blocky stuff","Hard stuff","Looks like food","Construction"], flavor: "Sour" },
  { id: 166, name: "Garganacl", number: "934", type: "Rock", specialty: ["Build","Crush"], location: "Sparkling Skylands", idealHabitat: "Dry", favourites: ["Stone stuff","Blocky stuff","Hard stuff","Construction","Luxury"], flavor: "Sour" },
  { id: 167, name: "Capsakid", number: "951", type: "Grass", specialty: ["Grow"], location: "Sparkling Skylands", idealHabitat: "Warm", favourites: ["Nature","Looks like food","Cute stuff","Fire","Group activities"], flavor: "Spicy" },
  { id: 168, name: "Scovillain", number: "952", type: "Grass/Fire", specialty: ["Grow","Burn"], location: "Sparkling Skylands", idealHabitat: "Warm", favourites: ["Nature","Looks like food","Fire","Colourful stuff","Luxury"], flavor: "Spicy" },
  { id: 169, name: "Toedscool", number: "948", type: "Ground/Grass", specialty: ["Grow"], location: "Palette Town", idealHabitat: "Humid", favourites: ["Nature","Dirt","Slender objects","Strange stuff","Group activities"], flavor: "Bitter" },
  { id: 170, name: "Toedscruel", number: "949", type: "Ground/Grass", specialty: ["Grow","Yawn"], location: "Palette Town", idealHabitat: "Humid", favourites: ["Nature","Dirt","Slender objects","Strange stuff","Complicated stuff"], flavor: "Bitter" },
  { id: 171, name: "Klawf", number: "950", type: "Rock", specialty: ["Build"], location: "Sparkling Skylands", idealHabitat: "Dry", favourites: ["Stone stuff","Exercise","Hard stuff","Sharp stuff","Group activities"], flavor: "Sour" },
  { id: 172, name: "Bramblin", number: "946", type: "Grass/Ghost", specialty: ["Grow"], location: "Sparkling Skylands", idealHabitat: "Dry", favourites: ["Nature","Nice breezes","Strange stuff","Dirt","Group activities"], flavor: "Bitter" },
  { id: 173, name: "Brambleghast", number: "947", type: "Grass/Ghost", specialty: ["Grow","Crush"], location: "Sparkling Skylands", idealHabitat: "Dry", favourites: ["Nature","Nice breezes","Strange stuff","Dirt","Luxury"], flavor: "Bitter" },
  { id: 174, name: "Shroodle", number: "944", type: "Poison/Normal", specialty: ["Trade"], location: "Palette Town", idealHabitat: "Bright", favourites: ["Colourful stuff","Cute stuff","Play spaces","Soft stuff","Group activities"], flavor: "Sour" },
  { id: 175, name: "Grafaiai", number: "945", type: "Poison/Normal", specialty: ["Trade"], location: "Palette Town", idealHabitat: "Bright", favourites: ["Colourful stuff","Wooden stuff","Play spaces","Nature","Luxury"], flavor: "Sour" },
  { id: 176, name: "Fidough", number: "926", type: "Fairy", specialty: ["Search"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Cute stuff","Looks like food","Soft stuff","Play spaces","Group activities"], flavor: "Sweet" },
  { id: 177, name: "Dachsbun", number: "927", type: "Fairy", specialty: ["Search"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Cute stuff","Looks like food","Soft stuff","Healing","Luxury"], flavor: "Sweet" },
  { id: 178, name: "Tandemaus", number: "924", type: "Normal", specialty: ["Trade"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Cute stuff","Group activities","Play spaces","Soft stuff","Looks like food"], flavor: "Sweet" },
  { id: 179, name: "Maushold", number: "925", type: "Normal", specialty: ["Trade","Hype"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Cute stuff","Group activities","Play spaces","Gatherings","Luxury"], flavor: "Sweet" },
  { id: 180, name: "Tadbulb", number: "938", type: "Electric", specialty: ["Generate"], location: "Bleak Beach", idealHabitat: "Humid", favourites: ["Electronics","Water","Shiny stuff","Round stuff","Group activities"], flavor: "Sour" },
  { id: 181, name: "Bellibolt", number: "939", type: "Electric", specialty: ["Generate","Yawn"], location: "Bleak Beach", idealHabitat: "Humid", favourites: ["Electronics","Water","Shiny stuff","Round stuff","Luxury"], flavor: "Sour" },
  { id: 182, name: "Varoom", number: "965", type: "Steel/Poison", specialty: ["Recycle"], location: "Palette Town", idealHabitat: "Bright", favourites: ["Metal stuff","Garbage","Noisy stuff","Exercise","Group activities"], flavor: "Spicy" },
  { id: 183, name: "Revavroom", number: "966", type: "Steel/Poison", specialty: ["Recycle","Bull"], location: "Palette Town", idealHabitat: "Bright", favourites: ["Metal stuff","Garbage","Noisy stuff","Rides","Luxury"], flavor: "Spicy" },
  { id: 184, name: "Orthworm", number: "968", type: "Steel", specialty: ["Crush"], location: "Rocky Ridges", idealHabitat: "Dry", favourites: ["Metal stuff","Dirt","Slender objects","Hard stuff","Group activities"], flavor: "Dry" },
  { id: 185, name: "Glimmet", number: "969", type: "Rock/Poison", specialty: ["Search"], location: "Palette Town", idealHabitat: "Dark", favourites: ["Stone stuff","Shiny stuff","Strange stuff","Colourful stuff","Group activities"], flavor: "Bitter" },
  { id: 186, name: "Glimmora", number: "970", type: "Rock/Poison", specialty: ["Search","Hype"], location: "Palette Town", idealHabitat: "Dark", favourites: ["Stone stuff","Shiny stuff","Pretty flowers","Colourful stuff","Luxury"], flavor: "Bitter" },
  { id: 187, name: "Cetoddle", number: "974", type: "Ice", specialty: ["Bull"], location: "Sparkling Skylands", idealHabitat: "Cold", favourites: ["Soft stuff","Cute stuff","Exercise","Round stuff","Group activities"], flavor: "Sweet" },
  { id: 188, name: "Cetitan", number: "975", type: "Ice", specialty: ["Bull","Crush"], location: "Sparkling Skylands", idealHabitat: "Cold", favourites: ["Soft stuff","Exercise","Rides","Round stuff","Luxury"], flavor: "Sweet" },
  { id: 189, name: "Dondozo", number: "977", type: "Water", specialty: ["Water"], location: "Sparkling Skylands", idealHabitat: "Humid", favourites: ["Water","Ocean vibes","Looks like food","Rides","Luxury"], flavor: "Dry" },
  { id: 190, name: "Tatsugiri", number: "978", type: "Dragon/Water", specialty: ["Water"], location: "Sparkling Skylands", idealHabitat: "Humid", favourites: ["Water","Looks like food","Cute stuff","Colourful stuff","Group activities"], flavor: "Sour" },
  { id: 191, name: "Iron Thorns", number: "995", type: "Rock/Electric", specialty: ["Generate","Crush"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Electronics","Metal stuff","Stone stuff","Hard stuff","Luxury"], flavor: "Bitter" },
  { id: 192, name: "Ogerpon", number: "1017", type: "Grass", specialty: ["Grow","Build"], location: "Sparkling Skylands", idealHabitat: "Bright", favourites: ["Nature","Pretty flowers","Construction","Colourful stuff","Luxury"], flavor: "Sweet" },
];

// Normalize favourite name to handle case differences
function normalizeFav(f) {
  return f.trim().toLowerCase();
}

// Get image URL from Serebii based on number
function getImageUrl(number) {
  return `https://www.serebii.net/pokemonpokopia/pokemon/small/${number}.png`;
}

// Build the full dataset
export const POKEMON_DATA = RAW_POKEMON.map(p => ({
  ...p,
  imageUrl: getImageUrl(p.number),
  favouritesNorm: p.favourites.map(normalizeFav),
  dataSource: "both",
}));

// Extract unique values for filters
export const ALL_TYPES = [...new Set(POKEMON_DATA.map(p => p.type))].sort();
export const ALL_SPECIALTIES = [...new Set(POKEMON_DATA.flatMap(p => p.specialty))].sort();
export const ALL_HABITATS = [...new Set(POKEMON_DATA.map(p => p.idealHabitat))].sort();
export const ALL_FAVOURITES = [...new Set(POKEMON_DATA.flatMap(p => p.favourites))].sort();
export const ALL_LOCATIONS = [...new Set(POKEMON_DATA.map(p => p.location))].sort();
export const ALL_FLAVORS = [...new Set(POKEMON_DATA.map(p => p.flavor))].sort();

export const TOWNS = [
  { id: "withered-wasteland", name: "Withered Wasteland", color: "bg-amber-100 text-amber-800", icon: "🏜️" },
  { id: "bleak-beach", name: "Bleak Beach", color: "bg-cyan-100 text-cyan-800", icon: "🏖️" },
  { id: "rocky-ridges", name: "Rocky Ridges", color: "bg-stone-100 text-stone-800", icon: "⛰️" },
  { id: "sparkling-skylands", name: "Sparkling Skylands", color: "bg-violet-100 text-violet-800", icon: "✨" },
  { id: "palette-town", name: "Palette Town", color: "bg-rose-100 text-rose-800", icon: "🎨" },
];

export function getPokemonById(id) {
  return POKEMON_DATA.find(p => p.id === id);
}

export function searchPokemon(query) {
  const q = query.toLowerCase();
  return POKEMON_DATA.filter(p => p.name.toLowerCase().includes(q));
}

export const DATA_STATS = {
  totalPokemon: POKEMON_DATA.length,
  totalFromSheet: POKEMON_DATA.length,
  totalFromSerebii: POKEMON_DATA.length,
  matched: POKEMON_DATA.length,
  partial: 0,
  failed: 0,
  lastRefresh: new Date().toISOString(),
};