// Pokémon Pokopia dataset — sourced from PokopiaPokemon.xlsx
// Fields: id (sequential), number (spreadsheet #), name, type, specialty[], location, idealHabitat, favourites[], flavor, imageUrl

const CUSTOM_IMAGES = {
  "pikachu (peakychu)": "https://media.base44.com/images/public/69b976fdec8fc338dd963cb9/8799afdb8_peakychu.png",
  "toxtricity (amped form)": "https://media.base44.com/images/public/69b976fdec8fc338dd963cb9/92ed96b4d_toxtricityampedform.png",
  "toxtricity (low key form)": "https://media.base44.com/images/public/69b976fdec8fc338dd963cb9/9a954560e_toxtricitylowkeyform.png",
  "snorlax (mosslax)": "https://media.base44.com/images/public/69b976fdec8fc338dd963cb9/0beca5076_snorlaxmosslax.png",
};

function getImageUrl(name) {
  const key = name.toLowerCase().trim();
  if (CUSTOM_IMAGES[key]) return CUSTOM_IMAGES[key];
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
  return `https://img.pokemondb.net/sprites/home/normal/2x/${slug}.jpg`;
}

function sp(str) {
  if (!str || str.trim() === '' || str.trim() === '???') return ['???'];
  return str.split(',').map(s => s.trim()).filter(Boolean);
}

function favs(f1, f2, f3, f4, f5) {
  return [f1, f2, f3, f4, f5]
    .map(f => (f || '').trim())
    .filter(f => f && f.toLowerCase() !== 'n/a' && f !== '');
}

function normalizeFav(f) { return f.trim().toLowerCase(); }

const RAW = [
  // --- Any ---
  { number: "047", name: "Ditto", type: "Normal", specialty: "Transform", location: "Any", idealHabitat: "Bright", f1: "N/a", f2: "N/a", f3: "N/a", f4: "N/a", f5: "N/a", flavor: "Neutral" },
  { number: "197.1", name: "Toxtricity (Amped Form)", type: "Electric/Poison", specialty: "Generate, Hype", location: "Any", idealHabitat: "Humid", f1: "Electronics", f2: "Play spaces", f3: "Noisy stuff", f4: "Slender objects", f5: "Sharp stuff", flavor: "Spicy" },
  { number: "197.2", name: "Toxtricity (Low Key Form)", type: "Electric/Poison", specialty: "Generate, Hype", location: "Any", idealHabitat: "Humid", f1: "Electronics", f2: "Play spaces", f3: "Noisy stuff", f4: "Slender objects", f5: "Sharp stuff", flavor: "Bitter" },
  { number: "201", name: "Armarouge", type: "Fire/Psychic", specialty: "Burn", location: "Any", idealHabitat: "Warm", f1: "Fire", f2: "Stone stuff", f3: "Strange stuff", f4: "Exercise", f5: "Luxury", flavor: "Spicy" },
  { number: "202", name: "Ceruledge", type: "Fire/Ghost", specialty: "Burn, Trade", location: "Any", idealHabitat: "Warm", f1: "Fire", f2: "Stone stuff", f3: "Spooky stuff", f4: "Strange stuff", f5: "Luxury", flavor: "Bitter" },
  { number: "271", name: "Aerodactyl", type: "Rock/Flying", specialty: "Fly", location: "Any", idealHabitat: "Bright", f1: "Stone stuff", f2: "Nice breezes", f3: "Hard stuff", f4: "Shiny stuff", f5: "Spinning stuff", flavor: "Sour" },
  { number: "272", name: "Cranidos", type: "Rock", specialty: "Crush", location: "Any", idealHabitat: "Dry", f1: "Stone stuff", f2: "Hard stuff", f3: "Wobbly stuff", f4: "Group activities", f5: "Exercise", flavor: "Spicy" },
  { number: "273", name: "Rampardos", type: "Rock", specialty: "Crush, Litter", location: "Any", idealHabitat: "Dry", f1: "Stone stuff", f2: "Hard stuff", f3: "Metal stuff", f4: "Luxury", f5: "Exercise", flavor: "Dry" },
  { number: "274", name: "Shieldon", type: "Rock/Steel", specialty: "Crush", location: "Any", idealHabitat: "Dry", f1: "Stone stuff", f2: "Hard stuff", f3: "Metal stuff", f4: "Luxury", f5: "Round stuff", flavor: "Sweet" },
  { number: "275", name: "Bastiodon", type: "Rock/Steel", specialty: "Crush, Litter", location: "Any", idealHabitat: "Dry", f1: "Stone stuff", f2: "Hard stuff", f3: "Metal stuff", f4: "Luxury", f5: "Exercise", flavor: "Bitter" },
  { number: "276", name: "Tyrunt", type: "Rock/Dragon", specialty: "Crush", location: "Any", idealHabitat: "Dark", f1: "Stone stuff", f2: "Hard stuff", f3: "Fire", f4: "Luxury", f5: "Exercise", flavor: "Sweet" },
  { number: "277", name: "Tyrantrum", type: "Rock/Dragon", specialty: "Crush, Litter", location: "Any", idealHabitat: "Dark", f1: "Stone stuff", f2: "Hard stuff", f3: "Fire", f4: "Luxury", f5: "Exercise", flavor: "Sour" },
  { number: "278", name: "Amaura", type: "Rock/Ice", specialty: "Crush", location: "Any", idealHabitat: "Humid", f1: "Stone stuff", f2: "Hard stuff", f3: "Shiny stuff", f4: "Group activities", f5: "Containers", flavor: "Dry" },
  { number: "279", name: "Aurorus", type: "Rock/Ice", specialty: "Crush, Litter", location: "Any", idealHabitat: "Humid", f1: "Stone stuff", f2: "Hard stuff", f3: "Shiny stuff", f4: "Noisy stuff", f5: "Symbols", flavor: "Sour" },
  // --- Any (Event) ---
  { number: "E1", name: "Hoppip", type: "Grass/Flying", specialty: "Grow", location: "Any (Event)", idealHabitat: "Bright", f1: "Soft stuff", f2: "Nature", f3: "Nice breezes", f4: "Pretty flowers", f5: "Wobbly stuff", flavor: "Sweet" },
  { number: "E2", name: "Skiploom", type: "Grass/Flying", specialty: "Grow", location: "Any (Event)", idealHabitat: "Bright", f1: "Soft stuff", f2: "Nature", f3: "Nice breezes", f4: "Pretty flowers", f5: "Spinning stuff", flavor: "Dry" },
  { number: "E3", name: "Jumpluff", type: "Grass/Flying", specialty: "Grow, Litter", location: "Any (Event)", idealHabitat: "Bright", f1: "Soft stuff", f2: "Nature", f3: "Nice breezes", f4: "Pretty flowers", f5: "Round stuff", flavor: "Sour" },
  { number: "E4", name: "Sableye", type: "Ghost/Dark", specialty: "Search", location: "Any (Event)", idealHabitat: "Dark", f1: "Spooky stuff", f2: "Shiny stuff", f3: "Luxury", f4: "Looks like food", f5: "Watching stuff", flavor: "Sour" },
  // --- Bleak Beach ---
  { number: "014", name: "Gloom", type: "Grass/Poison", specialty: "Grow", location: "Bleak Beach", idealHabitat: "Humid", f1: "Nature", f2: "Dirt", f3: "Soft stuff", f4: "Pretty flowers", f5: "Garbage", flavor: "Dry" },
  { number: "028", name: "Magneton", type: "Electric/Steel", specialty: "Generate", location: "Bleak Beach", idealHabitat: "Bright", f1: "Electronics", f2: "Metal stuff", f3: "Shiny stuff", f4: "Gatherings", f5: "Group activities", flavor: "Bitter" },
  { number: "029", name: "Magnezone", type: "Electric/Steel", specialty: "Generate, Recycle", location: "Bleak Beach", idealHabitat: "Bright", f1: "Electronics", f2: "Metal stuff", f3: "Luxury", f4: "Gatherings", f5: "Hard stuff", flavor: "Bitter" },
  { number: "079b", name: "Pikachu (Peakychu)", type: "Electric", specialty: "Illuminate", location: "Bleak Beach", idealHabitat: "Bright", f1: "Electronics", f2: "Glass stuff", f3: "Cute stuff", f4: "Healing", f5: "Letters/words", flavor: "Sweet" },
  { number: "081", name: "Zubat", type: "Poison/Flying", specialty: "Search", location: "Bleak Beach", idealHabitat: "Dark", f1: "Spooky stuff", f2: "Nice breezes", f3: "Wooden stuff", f4: "Noisy stuff", f5: "Complicated stuff", flavor: "Spicy" },
  { number: "082", name: "Golbat", type: "Poison/Flying", specialty: "Search", location: "Bleak Beach", idealHabitat: "Dark", f1: "Spooky stuff", f2: "Nice breezes", f3: "Wooden stuff", f4: "Noisy stuff", f5: "Complicated stuff", flavor: "Spicy" },
  { number: "083", name: "Crobat", type: "Poison/Flying", specialty: "Search, Chop", location: "Bleak Beach", idealHabitat: "Dark", f1: "Spooky stuff", f2: "Nice breezes", f3: "Wooden stuff", f4: "Garbage", f5: "Watching stuff", flavor: "Dry" },
  { number: "084", name: "Meowth", type: "Normal", specialty: "Trade", location: "Bleak Beach", idealHabitat: "Cool", f1: "Containers", f2: "Group activities", f3: "Shiny stuff", f4: "Glass stuff", f5: "Luxury", flavor: "Spicy" },
  { number: "086", name: "Psyduck", type: "Water", specialty: "Search", location: "Bleak Beach", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Strange stuff", f4: "Complicated stuff", f5: "Healing", flavor: "Dry" },
  { number: "087", name: "Golduck", type: "Water", specialty: "Search", location: "Bleak Beach", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Strange stuff", f4: "Complicated stuff", f5: "Sharp stuff", flavor: "Dry" },
  { number: "088", name: "Growlithe", type: "Fire", specialty: "Burn, Search", location: "Bleak Beach", idealHabitat: "Warm", f1: "Fire", f2: "Stone stuff", f3: "Nice breezes", f4: "Letters/words", f5: "Pretty flowers", flavor: "Sweet" },
  { number: "090", name: "Farfetch'd", type: "Normal/Flying", specialty: "Chop, Build", location: "Bleak Beach", idealHabitat: "Bright", f1: "Soft stuff", f2: "Nice breezes", f3: "Wooden stuff", f4: "Slender objects", f5: "Exercise", flavor: "Spicy" },
  { number: "091", name: "Grimer", type: "Poison", specialty: "Litter", location: "Bleak Beach", idealHabitat: "Humid", f1: "Garbage", f2: "Spooky stuff", f3: "Gatherings", f4: "Shiny stuff", f5: "Containers", flavor: "Bitter" },
  { number: "092", name: "Muk", type: "Poison", specialty: "Litter", location: "Bleak Beach", idealHabitat: "Humid", f1: "Garbage", f2: "Spooky stuff", f3: "Gatherings", f4: "Shiny stuff", f5: "Colourful stuff", flavor: "Bitter" },
  { number: "093", name: "Gastly", type: "Ghost/Poison", specialty: "Gather, Trade", location: "Bleak Beach", idealHabitat: "Dark", f1: "Spooky stuff", f2: "Strange stuff", f3: "Garbage", f4: "Containers", f5: "Group activities", flavor: "Spicy" },
  { number: "094", name: "Haunter", type: "Ghost/Poison", specialty: "Gather, Trade", location: "Bleak Beach", idealHabitat: "Dark", f1: "Spooky stuff", f2: "Strange stuff", f3: "Garbage", f4: "Wobbly stuff", f5: "Group activities", flavor: "Spicy" },
  { number: "095", name: "Gengar", type: "Ghost/Poison", specialty: "Gather, Trade", location: "Bleak Beach", idealHabitat: "Dark", f1: "Spooky stuff", f2: "Strange stuff", f3: "Garbage", f4: "Rides", f5: "Group activities", flavor: "Sweet" },
  { number: "096", name: "Voltorb", type: "Electric", specialty: "Generate, Explode", location: "Bleak Beach", idealHabitat: "Bright", f1: "Electronics", f2: "Shiny stuff", f3: "Round stuff", f4: "Colourful stuff", f5: "Spinning stuff", flavor: "Bitter" },
  { number: "097", name: "Electrode", type: "Electric", specialty: "Generate, Explode", location: "Bleak Beach", idealHabitat: "Bright", f1: "Electronics", f2: "Shiny stuff", f3: "Round stuff", f4: "Play spaces", f5: "Spinning stuff", flavor: "Sour" },
  { number: "098", name: "Exeggcute", type: "Grass/Psychic", specialty: "Grow, Teleport", location: "Bleak Beach", idealHabitat: "Bright", f1: "Nature", f2: "Strange stuff", f3: "Gatherings", f4: "Watching stuff", f5: "Group activities", flavor: "Spicy" },
  { number: "099", name: "Exeggutor", type: "Grass/Psychic", specialty: "Grow, Teleport", location: "Bleak Beach", idealHabitat: "Bright", f1: "Nature", f2: "Strange stuff", f3: "Gatherings", f4: "Watching stuff", f5: "Wooden stuff", flavor: "Dry" },
  { number: "100", name: "Happiny", type: "Normal", specialty: "Trade", location: "Bleak Beach", idealHabitat: "Bright", f1: "Soft stuff", f2: "Fabric", f3: "Healing", f4: "Round stuff", f5: "Containers", flavor: "Sweet" },
  { number: "101", name: "Chansey", type: "Normal", specialty: "Trade", location: "Bleak Beach", idealHabitat: "Bright", f1: "Soft stuff", f2: "Fabric", f3: "Healing", f4: "Round stuff", f5: "Group activities", flavor: "Sweet" },
  { number: "102", name: "Blissey", type: "Normal", specialty: "Trade, Litter", location: "Bleak Beach", idealHabitat: "Bright", f1: "Soft stuff", f2: "Fabric", f3: "Healing", f4: "Round stuff", f5: "Group activities", flavor: "Sour" },
  { number: "103", name: "Elekid", type: "Electric", specialty: "Generate", location: "Bleak Beach", idealHabitat: "Bright", f1: "Electronics", f2: "Glass stuff", f3: "Cute stuff", f4: "Round stuff", f5: "Spinning stuff", flavor: "Sweet" },
  { number: "104", name: "Electabuzz", type: "Electric", specialty: "Generate", location: "Bleak Beach", idealHabitat: "Bright", f1: "Electronics", f2: "Glass stuff", f3: "Fire", f4: "Sharp stuff", f5: "Exercise", flavor: "Spicy" },
  { number: "105", name: "Electivire", type: "Electric", specialty: "Generate, Crush", location: "Bleak Beach", idealHabitat: "Bright", f1: "Electronics", f2: "Glass stuff", f3: "Fire", f4: "Hard stuff", f5: "Exercise", flavor: "Sour" },
  { number: "106", name: "Lapras", type: "Water/Ice", specialty: "Water", location: "Bleak Beach", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Cleanliness", f4: "Watching stuff", f5: "Healing", flavor: "Sour" },
  { number: "108.1", name: "Snorlax (Mosslax)", type: "Normal", specialty: "Eat", location: "Bleak Beach", idealHabitat: "Bright", f1: "Soft stuff", f2: "Fabric", f3: "Looks like food", f4: "Watching stuff", f5: "Strange stuff", flavor: "Spicy" },
  { number: "109", name: "Spinarak", type: "Bug/Poison", specialty: "Litter", location: "Bleak Beach", idealHabitat: "Humid", f1: "Nature", f2: "Wooden stuff", f3: "Garbage", f4: "Rides", f5: "Colourful stuff", flavor: "Bitter" },
  { number: "110", name: "Ariados", type: "Bug/Poison", specialty: "Litter", location: "Bleak Beach", idealHabitat: "Humid", f1: "Nature", f2: "Wooden stuff", f3: "Garbage", f4: "Rides", f5: "Colourful stuff", flavor: "Sour" },
  { number: "111", name: "Mareep", type: "Electric", specialty: "Generate, Litter", location: "Bleak Beach", idealHabitat: "Bright", f1: "Electronics", f2: "Shiny stuff", f3: "Glass stuff", f4: "Cute stuff", f5: "Fabric", flavor: "Sweet" },
  { number: "112", name: "Flaaffy", type: "Electric", specialty: "Generate, Litter", location: "Bleak Beach", idealHabitat: "Bright", f1: "Electronics", f2: "Shiny stuff", f3: "Glass stuff", f4: "Cute stuff", f5: "Rides", flavor: "Bitter" },
  { number: "113", name: "Ampharos", type: "Electric", specialty: "Generate, Trade", location: "Bleak Beach", idealHabitat: "Bright", f1: "Electronics", f2: "Shiny stuff", f3: "Glass stuff", f4: "Cute stuff", f5: "Pretty flowers", flavor: "Sour" },
  { number: "114", name: "Azurill", type: "Normal/Fairy", specialty: "Water, Hype", location: "Bleak Beach", idealHabitat: "Humid", f1: "Water", f2: "Cute stuff", f3: "Cleanliness", f4: "Healing", f5: "Rides", flavor: "Sour" },
  { number: "115", name: "Marill", type: "Water/Fairy", specialty: "Water, Hype", location: "Bleak Beach", idealHabitat: "Humid", f1: "Water", f2: "Cute stuff", f3: "Cleanliness", f4: "Round stuff", f5: "Symbols", flavor: "Sour" },
  { number: "116", name: "Azumarill", type: "Water/Fairy", specialty: "Water, Build", location: "Bleak Beach", idealHabitat: "Humid", f1: "Water", f2: "Cute stuff", f3: "Construction", f4: "Wobbly stuff", f5: "Symbols", flavor: "Sour" },
  { number: "117", name: "P-Wooper", type: "Poison/Ground", specialty: "Litter", location: "Bleak Beach", idealHabitat: "Humid", f1: "Garbage", f2: "Dirt", f3: "Stone stuff", f4: "Cleanliness", f5: "Group activities", flavor: "Sour" },
  { number: "118", name: "Clodsire", type: "Poison/Ground", specialty: "Litter, Bull", location: "Bleak Beach", idealHabitat: "Humid", f1: "Garbage", f2: "Dirt", f3: "Water", f4: "Cleanliness", f5: "Round stuff", flavor: "Bitter" },
  { number: "119", name: "Smeargle", type: "Normal", specialty: "Paint", location: "Bleak Beach", idealHabitat: "Bright", f1: "Soft stuff", f2: "Fabric", f3: "Strange stuff", f4: "Colourful stuff", f5: "Shiny stuff", flavor: "Dry" },
  { number: "120", name: "Torchic", type: "Fire", specialty: "Burn", location: "Bleak Beach", idealHabitat: "Warm", f1: "Fire", f2: "Stone stuff", f3: "Cute stuff", f4: "Containers", f5: "Pretty flowers", flavor: "Sweet" },
  { number: "121", name: "Combusken", type: "Fire/Fighting", specialty: "Burn, Build", location: "Bleak Beach", idealHabitat: "Warm", f1: "Fire", f2: "Stone stuff", f3: "Exercise", f4: "Containers", f5: "Construction", flavor: "Spicy" },
  { number: "122", name: "Blaziken", type: "Fire/Fighting", specialty: "Burn, Build", location: "Bleak Beach", idealHabitat: "Warm", f1: "Fire", f2: "Luxury", f3: "Exercise", f4: "Containers", f5: "Construction", flavor: "Spicy" },
  { number: "123", name: "Wingull", type: "Water/Flying", specialty: "Water, Fly", location: "Bleak Beach", idealHabitat: "Bright", f1: "Water", f2: "Nice breezes", f3: "Cleanliness", f4: "Ocean vibes", f5: "Watching stuff", flavor: "Dry" },
  { number: "124", name: "Pelipper", type: "Water/Flying", specialty: "Water, Fly", location: "Bleak Beach", idealHabitat: "Bright", f1: "Water", f2: "Nice breezes", f3: "Cleanliness", f4: "Ocean vibes", f5: "Watching stuff", flavor: "Dry" },
  { number: "125", name: "Makuhita", type: "Fighting", specialty: "Build, Bull", location: "Bleak Beach", idealHabitat: "Bright", f1: "Exercise", f2: "Construction", f3: "Fabric", f4: "Round stuff", f5: "Wooden stuff", flavor: "Sweet" },
  { number: "126", name: "Hariyama", type: "Fighting", specialty: "Build, Bull", location: "Bleak Beach", idealHabitat: "Bright", f1: "Exercise", f2: "Construction", f3: "Fabric", f4: "Round stuff", f5: "Rides", flavor: "Spicy" },
  { number: "127", name: "Absol", type: "Dark", specialty: "Chop", location: "Bleak Beach", idealHabitat: "Bright", f1: "Soft stuff", f2: "Nice breezes", f3: "Letters/words", f4: "Complicated stuff", f5: "Exercise", flavor: "Dry" },
  { number: "128", name: "Piplup", type: "Water", specialty: "Water", location: "Bleak Beach", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Nice breezes", f4: "Cleanliness", f5: "Containers", flavor: "Sweet" },
  { number: "129", name: "Prinplup", type: "Water", specialty: "Water, Trade", location: "Bleak Beach", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Nice breezes", f4: "Cleanliness", f5: "Containers", flavor: "Dry" },
  { number: "130", name: "Empoleon", type: "Water/Steel", specialty: "Water, Trade", location: "Bleak Beach", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Metal stuff", f4: "Cleanliness", f5: "Letters/words", flavor: "Bitter" },
  { number: "131", name: "Audino", type: "Normal", specialty: "Trade", location: "Bleak Beach", idealHabitat: "Bright", f1: "Soft stuff", f2: "Fabric", f3: "Healing", f4: "Cute stuff", f5: "Round stuff", flavor: "Bitter" },
  { number: "132", name: "Trubbish", type: "Poison", specialty: "Recycle", location: "Bleak Beach", idealHabitat: "Dark", f1: "Garbage", f2: "Containers", f3: "Complicated stuff", f4: "Shiny stuff", f5: "Gatherings", flavor: "Bitter" },
  { number: "133", name: "Garbodor", type: "Poison", specialty: "Recycle, Litter", location: "Bleak Beach", idealHabitat: "Dark", f1: "Garbage", f2: "Containers", f3: "Complicated stuff", f4: "Shiny stuff", f5: "Gatherings", flavor: "Sour" },
  { number: "134", name: "Zorua", type: "Dark", specialty: "Trade", location: "Bleak Beach", idealHabitat: "Dark", f1: "Shiny stuff", f2: "Luxury", f3: "Glass stuff", f4: "Cute stuff", f5: "Group activities", flavor: "Sour" },
  { number: "135", name: "Zoroark", type: "Dark", specialty: "Trade, Chop", location: "Bleak Beach", idealHabitat: "Dark", f1: "Shiny stuff", f2: "Luxury", f3: "Glass stuff", f4: "Strange stuff", f5: "Group activities", flavor: "Spicy" },
  { number: "136", name: "Minccino", type: "Normal", specialty: "Gather", location: "Bleak Beach", idealHabitat: "Bright", f1: "Soft stuff", f2: "Fabric", f3: "Rides", f4: "Cute stuff", f5: "Cleanliness", flavor: "Sweet" },
  { number: "137", name: "Cinccino", type: "Normal", specialty: "Gather, Recycle", location: "Bleak Beach", idealHabitat: "Bright", f1: "Soft stuff", f2: "Fabric", f3: "Rides", f4: "Cute stuff", f5: "Cleanliness", flavor: "Sour" },
  { number: "138", name: "Grubbin", type: "Bug", specialty: "Chop", location: "Bleak Beach", idealHabitat: "Humid", f1: "Nature", f2: "Electronics", f3: "Watching stuff", f4: "Dirt", f5: "Containers", flavor: "Dry" },
  { number: "139", name: "Charjabug", type: "Bug/Electric", specialty: "Generate, Chop", location: "Bleak Beach", idealHabitat: "Humid", f1: "Nature", f2: "Electronics", f3: "Watching stuff", f4: "Glass stuff", f5: "Blocky stuff", flavor: "Bitter" },
  { number: "141", name: "Mimikyu", type: "Ghost/Fairy", specialty: "Trade", location: "Bleak Beach", idealHabitat: "Dark", f1: "Spooky stuff", f2: "Cute stuff", f3: "Electronics", f4: "Fabric", f5: "Group activities", flavor: "Bitter" },
  { number: "142", name: "Pawmi", type: "Electric", specialty: "Generate", location: "Bleak Beach", idealHabitat: "Bright", f1: "Electronics", f2: "Shiny stuff", f3: "Cute stuff", f4: "Glass stuff", f5: "Group activities", flavor: "Sweet" },
  { number: "143", name: "Pawmo", type: "Electric/Fighting", specialty: "Generate, Crush", location: "Bleak Beach", idealHabitat: "Bright", f1: "Electronics", f2: "Shiny stuff", f3: "Exercise", f4: "Glass stuff", f5: "Group activities", flavor: "Sweet" },
  { number: "144", name: "Pawmot", type: "Electric/Fighting", specialty: "Generate, Crush", location: "Bleak Beach", idealHabitat: "Bright", f1: "Electronics", f2: "Shiny stuff", f3: "Exercise", f4: "Healing", f5: "Group activities", flavor: "Dry" },
  { number: "145.1", name: "Tatsugiri (Curly)", type: "Water/Dragon", specialty: "Trade", location: "Bleak Beach", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Group activities", f4: "Slender objects", f5: "Gatherings", flavor: "Sour" },
  { number: "145.2", name: "Tatsugiri (Droopy)", type: "Water/Dragon", specialty: "Trade", location: "Bleak Beach", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Group activities", f4: "Spinning stuff", f5: "Blocky stuff", flavor: "Sweet" },
  { number: "145.3", name: "Tatsugiri (Stretchy)", type: "Water/Dragon", specialty: "Trade", location: "Bleak Beach", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Group activities", f4: "Letters/words", f5: "Containers", flavor: "Spicy" },
  // --- Dream Isle ---
  { number: "290", name: "Raikou", type: "Electric", specialty: "Generate", location: "Dream Isle", idealHabitat: "Bright", f1: "", f2: "", f3: "", f4: "", f5: "", flavor: "Neutral" },
  { number: "291", name: "Entei", type: "Fire", specialty: "Burn", location: "Dream Isle", idealHabitat: "Warm", f1: "", f2: "", f3: "", f4: "", f5: "", flavor: "Neutral" },
  { number: "292", name: "Suicune", type: "Water", specialty: "Water", location: "Dream Isle", idealHabitat: "Humid", f1: "", f2: "", f3: "", f4: "", f5: "", flavor: "Neutral" },
  { number: "299", name: "Mewtwo", type: "Psychic", specialty: "Teleport", location: "Dream Isle", idealHabitat: "Dark", f1: "Strange stuff", f2: "Watching stuff", f3: "Letters/words", f4: "Complicated stuff", f5: "Stone stuff", flavor: "Dry" },
  // --- Palette Town ---
  { number: "038", name: "Koffing", type: "Poison", specialty: "Recycle", location: "Palette Town", idealHabitat: "Dark", f1: "Garbage", f2: "Gatherings", f3: "Complicated stuff", f4: "Soft stuff", f5: "Wobbly stuff", flavor: "Bitter" },
  { number: "039", name: "Weezing", type: "Poison", specialty: "Recycle", location: "Palette Town", idealHabitat: "Dark", f1: "Garbage", f2: "Gatherings", f3: "Complicated stuff", f4: "Soft stuff", f5: "Wobbly stuff", flavor: "Bitter" },
  { number: "040", name: "Tangela", type: "Grass", specialty: "Grow, Litter", location: "Palette Town", idealHabitat: "Humid", f1: "Nature", f2: "Water", f3: "Gatherings", f4: "Pretty flowers", f5: "Slender objects", flavor: "Sour" },
  { number: "043", name: "Scizor", type: "Bug/Steel", specialty: "Chop", location: "Palette Town", idealHabitat: "Bright", f1: "Nature", f2: "Metal stuff", f3: "Wooden stuff", f4: "Hard stuff", f5: "Exercise", flavor: "Bitter" },
  { number: "077", name: "Cramorant", type: "Flying/Water", specialty: "Fly, Water", location: "Palette Town", idealHabitat: "Humid", f1: "Nice breezes", f2: "Water", f3: "Ocean vibes", f4: "Slender objects", f5: "Looks like food", flavor: "Bitter" },
  { number: "079", name: "Pikachu", type: "Electric", specialty: "Generate", location: "Palette Town", idealHabitat: "Bright", f1: "Electronics", f2: "Glass stuff", f3: "Group activities", f4: "Round stuff", f5: "Rides", flavor: "Sour" },
  { number: "107", name: "Munchlax", type: "Normal", specialty: "Bulldoze", location: "Palette Town", idealHabitat: "Bright", f1: "Soft stuff", f2: "Nature", f3: "Looks like food", f4: "Wobbly stuff", f5: "Group activities", flavor: "Dry" },
  { number: "108.2", name: "Snorlax", type: "Normal", specialty: "Trade, Bulldoze", location: "Palette Town", idealHabitat: "Warm", f1: "Soft stuff", f2: "Fabric", f3: "Looks like food", f4: "Wobbly stuff", f5: "Rides", flavor: "Dry" },
  { number: "156", name: "Machop", type: "Fighting", specialty: "Build, Gather", location: "Palette Town", idealHabitat: "Bright", f1: "Exercise", f2: "Construction", f3: "Stone stuff", f4: "Hard stuff", f5: "Group activities", flavor: "Spicy" },
  { number: "159", name: "Geodude", type: "Rock/Ground", specialty: "Crush", location: "Palette Town", idealHabitat: "Dry", f1: "Stone stuff", f2: "Hard stuff", f3: "Spinning stuff", f4: "Round stuff", f5: "Exercise", flavor: "Dry" },
  { number: "175", name: "Mawile", type: "Steel/Fairy", specialty: "Trade, Build", location: "Palette Town", idealHabitat: "Bright", f1: "Metal stuff", f2: "Cute stuff", f3: "Colourful stuff", f4: "Looks like food", f5: "Group activities", flavor: "Dry" },
  { number: "185", name: "Rowlet", type: "Grass/Flying", specialty: "Grow", location: "Palette Town", idealHabitat: "Bright", f1: "Nature", f2: "Wooden stuff", f3: "Nice breezes", f4: "Containers", f5: "Spinning stuff", flavor: "Dry" },
  { number: "191", name: "Skwovet", type: "Normal", specialty: "Search, Hype", location: "Palette Town", idealHabitat: "Bright", f1: "Soft stuff", f2: "Wooden stuff", f3: "Watching stuff", f4: "Looks like food", f5: "Round stuff", flavor: "Dry" },
  { number: "268", name: "Tinkatink", type: "Fairy/Steel", specialty: "Build", location: "Palette Town", idealHabitat: "Bright", f1: "Cute stuff", f2: "Metal stuff", f3: "Construction", f4: "Looks like food", f5: "Exercise", flavor: "Sweet" },
  { number: "269", name: "Tinkatuff", type: "Fairy/Steel", specialty: "Build", location: "Palette Town", idealHabitat: "Bright", f1: "Cute stuff", f2: "Metal stuff", f3: "Construction", f4: "Group activities", f5: "Exercise", flavor: "Sour" },
  { number: "280", name: "Eevee", type: "Normal", specialty: "Trade", location: "Palette Town", idealHabitat: "Bright", f1: "Soft stuff", f2: "Stone stuff", f3: "Cute stuff", f4: "Letters/words", f5: "Group activities", flavor: "Sweet" },
  { number: "281", name: "Vaporeon", type: "Water", specialty: "Water", location: "Palette Town", idealHabitat: "Humid", f1: "Water", f2: "Cleanliness", f3: "Cute stuff", f4: "Pretty flowers", f5: "Watching stuff", flavor: "Sweet" },
  { number: "282", name: "Jolteon", type: "Electric", specialty: "Generate", location: "Palette Town", idealHabitat: "Bright", f1: "Electronics", f2: "Shiny stuff", f3: "Cute stuff", f4: "Glass stuff", f5: "Sharp stuff", flavor: "Spicy" },
  { number: "283", name: "Flareon", type: "Fire", specialty: "Burn", location: "Palette Town", idealHabitat: "Warm", f1: "Fire", f2: "Wooden stuff", f3: "Cute stuff", f4: "Metal stuff", f5: "Rides", flavor: "Spicy" },
  { number: "284", name: "Espeon", type: "Psychic", specialty: "Gather", location: "Palette Town", idealHabitat: "Bright", f1: "Strange stuff", f2: "Nice breezes", f3: "Cute stuff", f4: "Complicated stuff", f5: "Watching stuff", flavor: "Sweet" },
  { number: "285", name: "Umbreon", type: "Dark", specialty: "Search", location: "Palette Town", idealHabitat: "Dark", f1: "Shiny stuff", f2: "Luxury", f3: "Cute stuff", f4: "Letters/words", f5: "Watching stuff", flavor: "Bitter" },
  { number: "286", name: "Leafeon", type: "Grass", specialty: "Grow", location: "Palette Town", idealHabitat: "Bright", f1: "Nature", f2: "Pretty flowers", f3: "Cute stuff", f4: "Fabric", f5: "Healing", flavor: "Sour" },
  { number: "287", name: "Glaceon", type: "Ice", specialty: "Trade", location: "Palette Town", idealHabitat: "Cool", f1: "Water", f2: "Shiny stuff", f3: "Cute stuff", f4: "Glass stuff", f5: "Group activities", flavor: "Sweet" },
  { number: "288", name: "Sylveon", type: "Fairy", specialty: "Hype", location: "Palette Town", idealHabitat: "Bright", f1: "Cute stuff", f2: "Nature", f3: "Fabric", f4: "Noisy stuff", f5: "Round stuff", flavor: "Sweet" },
  { number: "294", name: "Articuno", type: "Ice/Flying", specialty: "Fly", location: "Palette Town", idealHabitat: "Cool", f1: "Water", f2: "Nice breezes", f3: "Shiny stuff", f4: "Symbols", f5: "Luxury", flavor: "Sour" },
  { number: "295", name: "Zapdos", type: "Electric/Flying", specialty: "Fly", location: "Palette Town", idealHabitat: "Bright", f1: "Electronics", f2: "Nice breezes", f3: "Glass stuff", f4: "Symbols", f5: "Luxury", flavor: "Spicy" },
  { number: "296", name: "Moltres", type: "Fire/Flying", specialty: "Fly", location: "Palette Town", idealHabitat: "Warm", f1: "Fire", f2: "Nice breezes", f3: "Stone stuff", f4: "Symbols", f5: "Luxury", flavor: "Spicy" },
  // --- Rocky Ridges ---
  { number: "031", name: "Steelix", type: "Steel/Ground", specialty: "Crush, Bull", location: "Rocky Ridges", idealHabitat: "Dry", f1: "Metal stuff", f2: "Dirt", f3: "Stone stuff", f4: "Slender objects", f5: "Hard stuff", flavor: "Sour" },
  { number: "054", name: "Swalot", type: "Poison", specialty: "Storage", location: "Rocky Ridges", idealHabitat: "Humid", f1: "Garbage", f2: "Looks like food", f3: "Round stuff", f4: "Containers", f5: "Colourful stuff", flavor: "Bitter" },
  { number: "089", name: "Arcanine", type: "Fire", specialty: "Burn, Search", location: "Rocky Ridges", idealHabitat: "Warm", f1: "Fire", f2: "Stone stuff", f3: "Nice breezes", f4: "Watching stuff", f5: "Symbols", flavor: "Spicy" },
  { number: "146", name: "Ekans", type: "Poison", specialty: "Search", location: "Rocky Ridges", idealHabitat: "Dark", f1: "Garbage", f2: "Watching stuff", f3: "Nature", f4: "Slender objects", f5: "Spinning stuff", flavor: "Spicy" },
  { number: "147", name: "Arbok", type: "Poison", specialty: "Search", location: "Rocky Ridges", idealHabitat: "Dark", f1: "Garbage", f2: "Watching stuff", f3: "Nature", f4: "Slender objects", f5: "Spinning stuff", flavor: "Spicy" },
  { number: "148", name: "Cleffa", type: "Fairy", specialty: "Hype", location: "Rocky Ridges", idealHabitat: "Dark", f1: "Cute stuff", f2: "Round stuff", f3: "Colourful stuff", f4: "Healing", f5: "Rides", flavor: "Sweet" },
  { number: "149", name: "Clefairy", type: "Fairy", specialty: "Hype", location: "Rocky Ridges", idealHabitat: "Dark", f1: "Cute stuff", f2: "Play spaces", f3: "Pretty flowers", f4: "Healing", f5: "Group activities", flavor: "Sweet" },
  { number: "150", name: "Clefable", type: "Fairy", specialty: "Hype, Trade", location: "Rocky Ridges", idealHabitat: "Dark", f1: "Cute stuff", f2: "Play spaces", f3: "Pretty flowers", f4: "Healing", f5: "Group activities", flavor: "Sour" },
  { number: "151", name: "Igglybuff", type: "Normal/Fairy", specialty: "Hype", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Soft stuff", f2: "Cute stuff", f3: "Play spaces", f4: "Healing", f5: "Noisy stuff", flavor: "Sweet" },
  { number: "152", name: "Jigglypuff", type: "Normal/Fairy", specialty: "Hype", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Soft stuff", f2: "Cute stuff", f3: "Play spaces", f4: "Healing", f5: "Wobbly stuff", flavor: "Sweet" },
  { number: "153", name: "Wigglytuff", type: "Normal/Fairy", specialty: "Hype, Trade", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Soft stuff", f2: "Cute stuff", f3: "Play spaces", f4: "Healing", f5: "Group activities", flavor: "Sour" },
  { number: "154", name: "Diglett", type: "Ground", specialty: "Hype", location: "Rocky Ridges", idealHabitat: "Dark", f1: "Dirt", f2: "Play spaces", f3: "Cute stuff", f4: "Group activities", f5: "Slender objects", flavor: "Bitter" },
  { number: "155", name: "Dugtrio", type: "Ground", specialty: "Hype, Crush", location: "Rocky Ridges", idealHabitat: "Dark", f1: "Dirt", f2: "Play spaces", f3: "Gatherings", f4: "Group activities", f5: "Slender objects", flavor: "Spicy" },
  { number: "157", name: "Machoke", type: "Fighting", specialty: "Build, Gather", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Exercise", f2: "Construction", f3: "Stone stuff", f4: "Hard stuff", f5: "Group activities", flavor: "Sour" },
  { number: "158", name: "Machamp", type: "Fighting", specialty: "Build, Gather", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Exercise", f2: "Construction", f3: "Stone stuff", f4: "Hard stuff", f5: "Group activities", flavor: "Spicy" },
  { number: "160", name: "Graveler", type: "Rock/Ground", specialty: "Crush", location: "Rocky Ridges", idealHabitat: "Dry", f1: "Stone stuff", f2: "Hard stuff", f3: "Spinning stuff", f4: "Round stuff", f5: "Exercise", flavor: "Bitter" },
  { number: "161", name: "Golem", type: "Rock/Ground", specialty: "Crush, Trade", location: "Rocky Ridges", idealHabitat: "Dry", f1: "Stone stuff", f2: "Hard stuff", f3: "Spinning stuff", f4: "Round stuff", f5: "Exercise", flavor: "Sour" },
  { number: "163", name: "Magmar", type: "Fire", specialty: "Burn", location: "Rocky Ridges", idealHabitat: "Warm", f1: "Fire", f2: "Stone stuff", f3: "Electronics", f4: "Hard stuff", f5: "Exercise", flavor: "Sweet" },
  { number: "164", name: "Magmortar", type: "Fire", specialty: "Burn, Crush", location: "Rocky Ridges", idealHabitat: "Warm", f1: "Fire", f2: "Stone stuff", f3: "Electronics", f4: "Hard stuff", f5: "Exercise", flavor: "Dry" },
  { number: "165", name: "Bonsly", type: "Rock", specialty: "Bulldoze", location: "Rocky Ridges", idealHabitat: "Dry", f1: "Stone stuff", f2: "Hard stuff", f3: "Nature", f4: "Wooden stuff", f5: "Round stuff", flavor: "Sour" },
  { number: "166", name: "Sudowoodo", type: "Rock", specialty: "Trade", location: "Rocky Ridges", idealHabitat: "Dry", f1: "Stone stuff", f2: "Hard stuff", f3: "Nature", f4: "Wooden stuff", f5: "Watching stuff", flavor: "Dry" },
  { number: "167", name: "Murkrow", type: "Dark/Flying", specialty: "Trade, Fly", location: "Rocky Ridges", idealHabitat: "Dark", f1: "Shiny stuff", f2: "Nice breezes", f3: "Group activities", f4: "Luxury", f5: "Fabric", flavor: "Bitter" },
  { number: "168", name: "Honchkrow", type: "Dark/Flying", specialty: "Trade, Fly", location: "Rocky Ridges", idealHabitat: "Dark", f1: "Shiny stuff", f2: "Nice breezes", f3: "Spooky stuff", f4: "Letters/words", f5: "Glass stuff", flavor: "Bitter" },
  { number: "169", name: "Larvitar", type: "Rock/Ground", specialty: "Crush, Bull", location: "Rocky Ridges", idealHabitat: "Dry", f1: "Stone stuff", f2: "Dirt", f3: "Luxury", f4: "Shiny stuff", f5: "Looks like food", flavor: "Sweet" },
  { number: "171", name: "Tyranitar", type: "Rock/Ground", specialty: "Crush, Bull", location: "Rocky Ridges", idealHabitat: "Dry", f1: "Stone stuff", f2: "Hard stuff", f3: "Luxury", f4: "Shiny stuff", f5: "Exercise", flavor: "Spicy" },
  { number: "172", name: "Lotad", type: "Water/Grass", specialty: "Water", location: "Rocky Ridges", idealHabitat: "Humid", f1: "Water", f2: "Nature", f3: "Cleanliness", f4: "Containers", f5: "Noisy stuff", flavor: "Dry" },
  { number: "173", name: "Lombre", type: "Water/Grass", specialty: "Water", location: "Rocky Ridges", idealHabitat: "Humid", f1: "Water", f2: "Nature", f3: "Cleanliness", f4: "Containers", f5: "Noisy stuff", flavor: "Bitter" },
  { number: "174", name: "Ludicolo", type: "Water/Grass", specialty: "Water, Hype", location: "Rocky Ridges", idealHabitat: "Humid", f1: "Water", f2: "Nature", f3: "Play spaces", f4: "Containers", f5: "Noisy stuff", flavor: "Dry" },
  { number: "176", name: "Torkoal", type: "Fire", specialty: "Burn", location: "Rocky Ridges", idealHabitat: "Warm", f1: "Fire", f2: "Stone stuff", f3: "Metal stuff", f4: "Hard stuff", f5: "Watching stuff", flavor: "Dry" },
  { number: "177", name: "Kricketot", type: "Bug", specialty: "Hype", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Nature", f2: "Wooden stuff", f3: "Noisy stuff", f4: "Colourful stuff", f5: "Watching stuff", flavor: "Bitter" },
  { number: "178", name: "Kricketune", type: "Bug", specialty: "Hype", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Nature", f2: "Wooden stuff", f3: "Noisy stuff", f4: "Colourful stuff", f5: "Watching stuff", flavor: "Spicy" },
  { number: "179", name: "Chatot", type: "Normal/Flying", specialty: "Hype, Fly", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Nice breezes", f2: "Fabric", f3: "Slender objects", f4: "Play spaces", f5: "Noisy stuff", flavor: "Sweet" },
  { number: "180", name: "Riolu", type: "Fighting", specialty: "Build", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Exercise", f2: "Fabric", f3: "Construction", f4: "Gatherings", f5: "Watching stuff", flavor: "Spicy" },
  { number: "181", name: "Lucario", type: "Fighting/Steel", specialty: "Build", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Exercise", f2: "Metal stuff", f3: "Construction", f4: "Complicated stuff", f5: "Healing", flavor: "Dry" },
  { number: "182", name: "Rotom", type: "Electric/Ghost", specialty: "DJ", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Shiny stuff", f2: "Glass stuff", f3: "Noisy stuff", f4: "Group activities", f5: "Blocky stuff", flavor: "Bitter" },
  { number: "183", name: "Larvesta", type: "Bug/Fire", specialty: "Burn, Litter", location: "Rocky Ridges", idealHabitat: "Warm", f1: "Nature", f2: "Fire", f3: "Sharp stuff", f4: "Wooden stuff", f5: "Symbols", flavor: "Bitter" },
  { number: "184", name: "Volcarona", type: "Bug/Fire", specialty: "Burn, Litter", location: "Rocky Ridges", idealHabitat: "Warm", f1: "Nature", f2: "Fire", f3: "Letters/words", f4: "Wooden stuff", f5: "Symbols", flavor: "Dry" },
  { number: "186", name: "Dartrix", type: "Grass/Flying", specialty: "Grow, Chop", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Nature", f2: "Wooden stuff", f3: "Nice breezes", f4: "Slender objects", f5: "Cleanliness", flavor: "Sour" },
  { number: "187", name: "Decidueye", type: "Grass/Ghost", specialty: "Grow, Chop", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Nature", f2: "Spooky stuff", f3: "Wooden stuff", f4: "Nice breezes", f5: "Letters/words", flavor: "Dry" },
  { number: "188", name: "Scorbunny", type: "Fire", specialty: "Burn", location: "Rocky Ridges", idealHabitat: "Warm", f1: "Fire", f2: "Stone stuff", f3: "Soft stuff", f4: "Group activities", f5: "Sharp stuff", flavor: "Dry" },
  { number: "189", name: "Raboot", type: "Fire", specialty: "Burn", location: "Rocky Ridges", idealHabitat: "Warm", f1: "Fire", f2: "Stone stuff", f3: "Play spaces", f4: "Group activities", f5: "Containers", flavor: "Dry" },
  { number: "190", name: "Cinderace", type: "Fire", specialty: "Burn, Hype", location: "Rocky Ridges", idealHabitat: "Warm", f1: "Fire", f2: "Stone stuff", f3: "Play spaces", f4: "Group activities", f5: "Round stuff", flavor: "Spicy" },
  { number: "192", name: "Greedent", type: "Normal", specialty: "Party", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Soft stuff", f2: "Metal stuff", f3: "Group activities", f4: "Looks like food", f5: "Luxury", flavor: "Sweet" },
  { number: "193", name: "Rolycoly", type: "Rock", specialty: "Burn, Gather", location: "Rocky Ridges", idealHabitat: "Warm", f1: "Stone stuff", f2: "Fire", f3: "Hard stuff", f4: "Metal stuff", f5: "Rides", flavor: "Sour" },
  { number: "194", name: "Carkol", type: "Rock/Fire", specialty: "Burn, Gather", location: "Rocky Ridges", idealHabitat: "Warm", f1: "Stone stuff", f2: "Fire", f3: "Hard stuff", f4: "Metal stuff", f5: "Rides", flavor: "Spicy" },
  { number: "195", name: "Coalossal", type: "Rock/Fire", specialty: "Burn, Gather", location: "Rocky Ridges", idealHabitat: "Warm", f1: "Stone stuff", f2: "Fire", f3: "Hard stuff", f4: "Metal stuff", f5: "Rides", flavor: "Spicy" },
  { number: "196", name: "Toxel", type: "Electric/Poison", specialty: "Generate", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Electronics", f2: "Shiny stuff", f3: "Noisy stuff", f4: "Glass stuff", f5: "Garbage", flavor: "Sweet" },
  { number: "198", name: "Fidough", type: "Fairy", specialty: "Search", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Cute stuff", f2: "Watching stuff", f3: "Soft stuff", f4: "Fire", f5: "Letters/words", flavor: "Sweet" },
  { number: "199", name: "Dachsbun", type: "Fairy", specialty: "Search, Trade", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Cute stuff", f2: "Watching stuff", f3: "Group activities", f4: "Fire", f5: "Looks like food", flavor: "Sour" },
  { number: "200", name: "Charcadet", type: "Fire", specialty: "Burn", location: "Rocky Ridges", idealHabitat: "Warm", f1: "Fire", f2: "Stone stuff", f3: "Strange stuff", f4: "Exercise", f5: "Luxury", flavor: "Sweet" },
  { number: "203", name: "Glimmet", type: "Rock/Poison", specialty: "Litter", location: "Rocky Ridges", idealHabitat: "Dark", f1: "Stone stuff", f2: "Hard stuff", f3: "Garbage", f4: "Shiny stuff", f5: "Complicated stuff", flavor: "Bitter" },
  { number: "204", name: "Glimmora", type: "Rock/Poison", specialty: "Litter", location: "Rocky Ridges", idealHabitat: "Dark", f1: "Stone stuff", f2: "Hard stuff", f3: "Garbage", f4: "Shiny stuff", f5: "Complicated stuff", flavor: "Bitter" },
  { number: "205", name: "Gimmighoul", type: "Ghost", specialty: "Collect", location: "Rocky Ridges", idealHabitat: "Dark", f1: "Spooky stuff", f2: "Metal stuff", f3: "Strange stuff", f4: "Shiny stuff", f5: "Complicated stuff", flavor: "Bitter" },
  { number: "206", name: "Gholdengo", type: "Steel/Ghost", specialty: "Collect", location: "Rocky Ridges", idealHabitat: "Bright", f1: "Spooky stuff", f2: "Metal stuff", f3: "Strange stuff", f4: "Shiny stuff", f5: "Complicated stuff", flavor: "Dry" },
  { number: "212", name: "Politoed", type: "Water", specialty: "Water, Hype", location: "Rocky Ridges", idealHabitat: "Humid", f1: "Water", f2: "Play spaces", f3: "Noisy stuff", f4: "Gatherings", f5: "Group activities", flavor: "Sour" },
  { number: "293", name: "Volcanion", type: "Fire/Water", specialty: "Burn", location: "Rocky Ridges", idealHabitat: "Warm", f1: "Fire", f2: "Water", f3: "Stone stuff", f4: "Containers", f5: "Symbols", flavor: "Spicy" },
  // --- Sparkling Skylands ---
  { number: "046", name: "Gyarados", type: "Water/Flying", specialty: "Water", location: "Sparkling Skylands", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Nice breezes", f4: "Cleanliness", f5: "Slender objects", flavor: "Spicy" },
  { number: "062", name: "Drifblim", type: "Ghost/Flying", specialty: "Fly, Gather", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Spooky stuff", f2: "Strange stuff", f3: "Nice breezes", f4: "Wobbly stuff", f5: "Spinning stuff", flavor: "Bitter" },
  { number: "067", name: "Conkeldurr", type: "Fighting", specialty: "Build, Crush", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Exercise", f2: "Construction", f3: "Stone stuff", f4: "Slender objects", f5: "Group activities", flavor: "Spicy" },
  { number: "080", name: "Raichu", type: "Electric", specialty: "Generate, Hype", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Electronics", f2: "Glass stuff", f3: "Group activities", f4: "Round stuff", f5: "Play spaces", flavor: "Sour" },
  { number: "085", name: "Persian", type: "Normal", specialty: "Trade, Search", location: "Sparkling Skylands", idealHabitat: "Cool", f1: "Containers", f2: "Group activities", f3: "Shiny stuff", f4: "Watching stuff", f5: "Luxury", flavor: "Sour" },
  { number: "170", name: "Pupitar", type: "Rock/Ground", specialty: "Crush, Bull", location: "Sparkling Skylands", idealHabitat: "Dry", f1: "Stone stuff", f2: "Hard stuff", f3: "Luxury", f4: "Shiny stuff", f5: "Watching stuff", flavor: "Dry" },
  { number: "207", name: "Vulpix", type: "Fire", specialty: "Burn", location: "Sparkling Skylands", idealHabitat: "Warm", f1: "Fire", f2: "Soft stuff", f3: "Cute stuff", f4: "Round stuff", f5: "Pretty flowers", flavor: "Bitter" },
  { number: "208", name: "Ninetales", type: "Fire", specialty: "Burn", location: "Sparkling Skylands", idealHabitat: "Warm", f1: "Fire", f2: "Soft stuff", f3: "Watching stuff", f4: "Luxury", f5: "Pretty flowers", flavor: "Dry" },
  { number: "209", name: "Poliwag", type: "Water", specialty: "Water", location: "Sparkling Skylands", idealHabitat: "Humid", f1: "Water", f2: "Cleanliness", f3: "Round stuff", f4: "Rides", f5: "Spinning stuff", flavor: "Sweet" },
  { number: "210", name: "Poliwhirl", type: "Water", specialty: "Water", location: "Sparkling Skylands", idealHabitat: "Humid", f1: "Water", f2: "Cleanliness", f3: "Nature", f4: "Exercise", f5: "Spinning stuff", flavor: "Bitter" },
  { number: "211", name: "Poliwrath", type: "Water/Fighting", specialty: "Water, Build", location: "Sparkling Skylands", idealHabitat: "Humid", f1: "Water", f2: "Cleanliness", f3: "Construction", f4: "Exercise", f5: "Group activities", flavor: "Spicy" },
  { number: "213", name: "Abra", type: "Psychic", specialty: "Teleport", location: "Sparkling Skylands", idealHabitat: "Dark", f1: "Strange stuff", f2: "Wobbly stuff", f3: "Metal stuff", f4: "Soft stuff", f5: "Watching stuff", flavor: "Dry" },
  { number: "214", name: "Kadabra", type: "Psychic", specialty: "Teleport", location: "Sparkling Skylands", idealHabitat: "Dark", f1: "Strange stuff", f2: "Wobbly stuff", f3: "Metal stuff", f4: "Containers", f5: "Watching stuff", flavor: "Dry" },
  { number: "215", name: "Alakazam", type: "Psychic", specialty: "Teleport, Trade", location: "Sparkling Skylands", idealHabitat: "Dark", f1: "Strange stuff", f2: "Wobbly stuff", f3: "Metal stuff", f4: "Letters/words", f5: "Watching stuff", flavor: "Bitter" },
  { number: "216", name: "Mime Jr.", type: "Psychic/Fairy", specialty: "Gather", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Strange stuff", f2: "Cute stuff", f3: "Rides", f4: "Play spaces", f5: "Colourful stuff", flavor: "Sweet" },
  { number: "217", name: "Mr. Mime", type: "Psychic/Fairy", specialty: "Gather, Build", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Strange stuff", f2: "Cute stuff", f3: "Rides", f4: "Wobbly stuff", f5: "Watching stuff", flavor: "Bitter" },
  { number: "218", name: "Porygon", type: "Normal", specialty: "Recycle", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Soft stuff", f2: "Strange stuff", f3: "Blocky stuff", f4: "Construction", f5: "Colourful stuff", flavor: "Bitter" },
  { number: "219", name: "Porygon2", type: "Normal", specialty: "Recycle", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Soft stuff", f2: "Strange stuff", f3: "Round stuff", f4: "Construction", f5: "Colourful stuff", flavor: "Sour" },
  { number: "220", name: "Porygon-Z", type: "Normal", specialty: "Rarify", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Soft stuff", f2: "Strange stuff", f3: "Fabric", f4: "Watching stuff", f5: "Colourful stuff", flavor: "Dry" },
  { number: "221", name: "Dratini", type: "Dragon", specialty: "Water", location: "Sparkling Skylands", idealHabitat: "Humid", f1: "Water", f2: "Fire", f3: "Cleanliness", f4: "Cute stuff", f5: "Slender objects", flavor: "Sweet" },
  { number: "222", name: "Dragonair", type: "Dragon", specialty: "Water", location: "Sparkling Skylands", idealHabitat: "Humid", f1: "Water", f2: "Fire", f3: "Cleanliness", f4: "Glass stuff", f5: "Slender objects", flavor: "Sweet" },
  { number: "223", name: "Dragonite", type: "Dragon/Flying", specialty: "Water, Fly", location: "Sparkling Skylands", idealHabitat: "Humid", f1: "Fire", f2: "Nice breezes", f3: "Cleanliness", f4: "Symbols", f5: "Pretty flowers", flavor: "Dry" },
  { number: "224", name: "Cyndaquil", type: "Fire", specialty: "Burn", location: "Sparkling Skylands", idealHabitat: "Warm", f1: "Fire", f2: "Fabric", f3: "Slender objects", f4: "Metal stuff", f5: "Rides", flavor: "Sweet" },
  { number: "225", name: "Quilava", type: "Fire", specialty: "Burn", location: "Sparkling Skylands", idealHabitat: "Warm", f1: "Fire", f2: "Fabric", f3: "Slender objects", f4: "Metal stuff", f5: "Rides", flavor: "Sweet" },
  { number: "226", name: "Typhlosion", type: "Fire", specialty: "Burn, Trade", location: "Sparkling Skylands", idealHabitat: "Warm", f1: "Fire", f2: "Fabric", f3: "Slender objects", f4: "Metal stuff", f5: "Rides", flavor: "Dry" },
  { number: "227", name: "Misdreavus", type: "Ghost", specialty: "Trade", location: "Sparkling Skylands", idealHabitat: "Dark", f1: "Spooky stuff", f2: "Strange stuff", f3: "Shiny stuff", f4: "Colourful stuff", f5: "Watching stuff", flavor: "Dry" },
  { number: "228", name: "Mismagius", type: "Ghost", specialty: "Gather, Trade", location: "Sparkling Skylands", idealHabitat: "Dark", f1: "Spooky stuff", f2: "Strange stuff", f3: "Noisy stuff", f4: "Wobbly stuff", f5: "Group activities", flavor: "Bitter" },
  { number: "229", name: "Girafarig", type: "Normal/Psychic", specialty: "Gather", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Soft stuff", f2: "Strange stuff", f3: "Rides", f4: "Watching stuff", f5: "Slender objects", flavor: "Sour" },
  { number: "230", name: "Farigiraf", type: "Normal/Psychic", specialty: "Gather, Search", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Soft stuff", f2: "Strange stuff", f3: "Rides", f4: "Watching stuff", f5: "Slender objects", flavor: "Sour" },
  { number: "231", name: "Ralts", type: "Psychic/Fairy", specialty: "Teleport", location: "Sparkling Skylands", idealHabitat: "Dark", f1: "Strange stuff", f2: "Cute stuff", f3: "Healing", f4: "Watching stuff", f5: "Symbols", flavor: "Sweet" },
  { number: "232", name: "Kirlia", type: "Psychic/Fairy", specialty: "Teleport", location: "Sparkling Skylands", idealHabitat: "Dark", f1: "Strange stuff", f2: "Cute stuff", f3: "Healing", f4: "Watching stuff", f5: "Symbols", flavor: "Sweet" },
  { number: "233", name: "Gardevoir", type: "Psychic/Fairy", specialty: "Teleport, Trade", location: "Sparkling Skylands", idealHabitat: "Dark", f1: "Strange stuff", f2: "Luxury", f3: "Healing", f4: "Watching stuff", f5: "Symbols", flavor: "Sour" },
  { number: "234", name: "Gallade", type: "Psychic/Fighting", specialty: "Teleport, Build", location: "Sparkling Skylands", idealHabitat: "Dark", f1: "Strange stuff", f2: "Exercise", f3: "Healing", f4: "Construction", f5: "Fabric", flavor: "Spicy" },
  { number: "235", name: "Plusle", type: "Electric", specialty: "Generate", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Electronics", f2: "Glass stuff", f3: "Soft stuff", f4: "Cute stuff", f5: "Group activities", flavor: "Sweet" },
  { number: "236", name: "Minun", type: "Electric", specialty: "Generate", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Electronics", f2: "Glass stuff", f3: "Soft stuff", f4: "Cute stuff", f5: "Group activities", flavor: "Spicy" },
  { number: "237", name: "Trapinch", type: "Ground", specialty: "Bull, Litter", location: "Sparkling Skylands", idealHabitat: "Dry", f1: "Dirt", f2: "Hard stuff", f3: "Strange stuff", f4: "Watching stuff", f5: "Exercise", flavor: "Spicy" },
  { number: "238", name: "Vibrava", type: "Ground/Dragon", specialty: "Bull, Fly", location: "Sparkling Skylands", idealHabitat: "Dry", f1: "Dirt", f2: "Fire", f3: "Nature", f4: "Luxury", f5: "Noisy stuff", flavor: "Bitter" },
  { number: "239", name: "Flygon", type: "Ground/Dragon", specialty: "Bull, Fly", location: "Sparkling Skylands", idealHabitat: "Dry", f1: "Dirt", f2: "Fire", f3: "Nature", f4: "Stone stuff", f5: "Wooden stuff", flavor: "Sour" },
  { number: "240", name: "Swablu", type: "Normal/Flying", specialty: "Litter", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Soft stuff", f2: "Nice breezes", f3: "Cute stuff", f4: "Watching stuff", f5: "Cleanliness", flavor: "Sweet" },
  { number: "241", name: "Altaria", type: "Dragon/Flying", specialty: "Litter, Fly", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Soft stuff", f2: "Nice breezes", f3: "Cute stuff", f4: "Watching stuff", f5: "Noisy stuff", flavor: "Sour" },
  { number: "242", name: "Duskull", type: "Ghost", specialty: "Gather", location: "Sparkling Skylands", idealHabitat: "Dark", f1: "Spooky stuff", f2: "Strange stuff", f3: "Rides", f4: "Glass stuff", f5: "Fabric", flavor: "Bitter" },
  { number: "243", name: "Dusclops", type: "Ghost", specialty: "Gather", location: "Sparkling Skylands", idealHabitat: "Dark", f1: "Spooky stuff", f2: "Strange stuff", f3: "Rides", f4: "Soft stuff", f5: "Containers", flavor: "Sour" },
  { number: "244", name: "Dusknoir", type: "Ghost", specialty: "Gather, Trade", location: "Sparkling Skylands", idealHabitat: "Dark", f1: "Spooky stuff", f2: "Strange stuff", f3: "Rides", f4: "Group activities", f5: "Containers", flavor: "Bitter" },
  { number: "245", name: "Beldum", type: "Steel/Psychic", specialty: "Recycle", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Metal stuff", f2: "Strange stuff", f3: "Hard stuff", f4: "Complicated stuff", f5: "Stone stuff", flavor: "Sour" },
  { number: "246", name: "Metang", type: "Steel/Psychic", specialty: "Recycle", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Metal stuff", f2: "Strange stuff", f3: "Hard stuff", f4: "Complicated stuff", f5: "Stone stuff", flavor: "Bitter" },
  { number: "247", name: "Metagross", type: "Steel/Psychic", specialty: "Crush, Recycle", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Metal stuff", f2: "Strange stuff", f3: "Hard stuff", f4: "Exercise", f5: "Luxury", flavor: "Dry" },
  { number: "248", name: "Snivy", type: "Grass", specialty: "Grow, Litter", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Nature", f2: "Wooden stuff", f3: "Water", f4: "Wobbly stuff", f5: "Shiny stuff", flavor: "Sour" },
  { number: "249", name: "Servine", type: "Grass", specialty: "Grow, Litter", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Nature", f2: "Wooden stuff", f3: "Water", f4: "Cleanliness", f5: "Shiny stuff", flavor: "Bitter" },
  { number: "250", name: "Serperior", type: "Grass", specialty: "Grow, Litter", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Nature", f2: "Wooden stuff", f3: "Water", f4: "Containers", f5: "Slender objects", flavor: "Dry" },
  { number: "251", name: "Froakie", type: "Water", specialty: "Water", location: "Sparkling Skylands", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Cleanliness", f4: "Watching stuff", f5: "Containers", flavor: "Spicy" },
  { number: "252", name: "Frogadier", type: "Water", specialty: "Water", location: "Sparkling Skylands", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Cleanliness", f4: "Watching stuff", f5: "Exercise", flavor: "Spicy" },
  { number: "253", name: "Greninja", type: "Water/Dark", specialty: "Water, Chop", location: "Sparkling Skylands", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Cleanliness", f4: "Shiny stuff", f5: "Exercise", flavor: "Bitter" },
  { number: "254", name: "Dedenne", type: "Electric/Fairy", specialty: "Search", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Electronics", f2: "Cute stuff", f3: "Watching stuff", f4: "Group activities", f5: "Looks like food", flavor: "Sweet" },
  { number: "255", name: "Noibat", type: "Flying/Dragon", specialty: "Search", location: "Sparkling Skylands", idealHabitat: "Dark", f1: "Nice breezes", f2: "Fabric", f3: "Watching stuff", f4: "Luxury", f5: "Looks like food", flavor: "Spicy" },
  { number: "256", name: "Noivern", type: "Flying/Dragon", specialty: "Search, Fly", location: "Sparkling Skylands", idealHabitat: "Dark", f1: "Nice breezes", f2: "Fire", f3: "Watching stuff", f4: "Play spaces", f5: "Looks like food", flavor: "Dry" },
  { number: "257", name: "Rookidee", type: "Flying", specialty: "Chop", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Nice breezes", f2: "Shiny stuff", f3: "Containers", f4: "Slender objects", f5: "Wooden stuff", flavor: "Sour" },
  { number: "258", name: "Corvisquire", type: "Flying", specialty: "Chop", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Nice breezes", f2: "Shiny stuff", f3: "Containers", f4: "Slender objects", f5: "Wooden stuff", flavor: "Dry" },
  { number: "259", name: "Corviknight", type: "Flying/Steel", specialty: "Chop, Fly", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Nice breezes", f2: "Metal stuff", f3: "Shiny stuff", f4: "Containers", f5: "Wooden stuff", flavor: "Bitter" },
  { number: "260", name: "Dreepy", type: "Ghost/Dragon", specialty: "Gather, Search", location: "Sparkling Skylands", idealHabitat: "Dark", f1: "Fire", f2: "Spooky stuff", f3: "Rides", f4: "Strange stuff", f5: "Group activities", flavor: "Spicy" },
  { number: "261", name: "Drakloak", type: "Ghost/Dragon", specialty: "Gather, Search", location: "Sparkling Skylands", idealHabitat: "Dark", f1: "Fire", f2: "Spooky stuff", f3: "Rides", f4: "Strange stuff", f5: "Group activities", flavor: "Sweet" },
  { number: "262", name: "Dragapult", type: "Ghost/Dragon", specialty: "Gather, Trade", location: "Sparkling Skylands", idealHabitat: "Dark", f1: "Fire", f2: "Spooky stuff", f3: "Rides", f4: "Strange stuff", f5: "Group activities", flavor: "Spicy" },
  { number: "263", name: "Sprigatito", type: "Grass", specialty: "Grow", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Nature", f2: "Pretty flowers", f3: "Containers", f4: "Colourful stuff", f5: "Cute stuff", flavor: "Sweet" },
  { number: "264", name: "Floragato", type: "Grass", specialty: "Grow", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Nature", f2: "Pretty flowers", f3: "Sharp stuff", f4: "Colourful stuff", f5: "Cute stuff", flavor: "Sour" },
  { number: "265", name: "Meowscarada", type: "Grass/Dark", specialty: "Hype", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Nature", f2: "Pretty flowers", f3: "Shiny stuff", f4: "Luxury", f5: "Cute stuff", flavor: "Dry" },
  { number: "266", name: "Wattrel", type: "Electric/Flying", specialty: "Generate", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Electronics", f2: "Nice breezes", f3: "Ocean vibes", f4: "Gatherings", f5: "Complicated stuff", flavor: "Spicy" },
  { number: "267", name: "Kilowattrel", type: "Electric/Flying", specialty: "Generate, Fly", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Electronics", f2: "Nice breezes", f3: "Ocean vibes", f4: "Gatherings", f5: "Slender objects", flavor: "Dry" },
  { number: "270", name: "Tinkaton", type: "Fairy/Steel", specialty: "Engineer", location: "Sparkling Skylands", idealHabitat: "Bright", f1: "Cute stuff", f2: "Metal stuff", f3: "Construction", f4: "Blocky stuff", f5: "Exercise", flavor: "Spicy" },
  // --- Withered Wasteland ---
  { number: "001", name: "Bulbasaur", type: "Grass/Poison", specialty: "Grow", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Nature", f2: "Soft stuff", f3: "Cute stuff", f4: "Water", f5: "Group activities", flavor: "Sweet" },
  { number: "002", name: "Ivysaur", type: "Grass/Poison", specialty: "Grow", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Nature", f2: "Soft stuff", f3: "Cute stuff", f4: "Pretty flowers", f5: "Group activities", flavor: "Sour" },
  { number: "003", name: "Venusaur", type: "Grass/Poison", specialty: "Grow, Litter", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Nature", f2: "Soft stuff", f3: "Cute stuff", f4: "Pretty flowers", f5: "Luxury", flavor: "Sour" },
  { number: "004", name: "Charmander", type: "Fire", specialty: "Burn", location: "Withered Wasteland", idealHabitat: "Warm", f1: "Fire", f2: "Wooden stuff", f3: "Hard stuff", f4: "Exercise", f5: "Group activities", flavor: "Spicy" },
  { number: "005", name: "Charmeleon", type: "Fire", specialty: "Burn", location: "Withered Wasteland", idealHabitat: "Warm", f1: "Fire", f2: "Wooden stuff", f3: "Hard stuff", f4: "Exercise", f5: "Rides", flavor: "Spicy" },
  { number: "006", name: "Charizard", type: "Fire/Flying", specialty: "Burn, Fly", location: "Withered Wasteland", idealHabitat: "Warm", f1: "Fire", f2: "Nice breezes", f3: "Wooden stuff", f4: "Exercise", f5: "Luxury", flavor: "Spicy" },
  { number: "007", name: "Squirtle", type: "Water", specialty: "Water", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Water", f2: "Cleanliness", f3: "Healing", f4: "Cute stuff", f5: "Group activities", flavor: "Sweet" },
  { number: "008", name: "Wartortle", type: "Water", specialty: "Water", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Water", f2: "Cleanliness", f3: "Healing", f4: "Exercise", f5: "Hard stuff", flavor: "Spicy" },
  { number: "009", name: "Blastoise", type: "Water", specialty: "Water, Trade", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Water", f2: "Cleanliness", f3: "Healing", f4: "Exercise", f5: "Luxury", flavor: "Sour" },
  { number: "010", name: "Pidgey", type: "Normal/Flying", specialty: "Fly, Search", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Soft stuff", f2: "Nice breezes", f3: "Watching stuff", f4: "Nature", f5: "Play spaces", flavor: "Sour" },
  { number: "011", name: "Pidgeotto", type: "Normal/Flying", specialty: "Fly, Search", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Soft stuff", f2: "Nice breezes", f3: "Watching stuff", f4: "Nature", f5: "Looks like food", flavor: "Spicy" },
  { number: "012", name: "Pidgeot", type: "Normal/Flying", specialty: "Chop, Fly", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Soft stuff", f2: "Nice breezes", f3: "Wooden stuff", f4: "Nature", f5: "Luxury", flavor: "Sour" },
  { number: "013", name: "Oddish", type: "Grass/Poison", specialty: "Grow", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Nature", f2: "Dirt", f3: "Soft stuff", f4: "Pretty flowers", f5: "Water", flavor: "Bitter" },
  { number: "015", name: "Vileplume", type: "Grass/Poison", specialty: "Grow, Litter", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Nature", f2: "Dirt", f3: "Soft stuff", f4: "Pretty flowers", f5: "Colourful stuff", flavor: "Bitter" },
  { number: "016", name: "Bellossom", type: "Grass", specialty: "Grow, Hype", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Nature", f2: "Pretty flowers", f3: "Play spaces", f4: "Cute stuff", f5: "Noisy stuff", flavor: "Sour" },
  { number: "017", name: "Paras", type: "Bug/Grass", specialty: "Search", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Nature", f2: "Wooden stuff", f3: "Watching stuff", f4: "Dirt", f5: "Looks like food", flavor: "Bitter" },
  { number: "018", name: "Parasect", type: "Bug/Grass", specialty: "Search", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Nature", f2: "Wooden stuff", f3: "Watching stuff", f4: "Dirt", f5: "Strange stuff", flavor: "Bitter" },
  { number: "019", name: "Venonat", type: "Bug/Poison", specialty: "Search", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Nature", f2: "Wooden stuff", f3: "Watching stuff", f4: "Complicated stuff", f5: "Letters/words", flavor: "Bitter" },
  { number: "020", name: "Venomoth", type: "Bug/Poison", specialty: "Search", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Nature", f2: "Wooden stuff", f3: "Watching stuff", f4: "Nice breezes", f5: "Pretty flowers", flavor: "Bitter" },
  { number: "021", name: "Bellsprout", type: "Grass/Poison", specialty: "Grow, Litter", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Nature", f2: "Wooden stuff", f3: "Dirt", f4: "Water", f5: "Pretty flowers", flavor: "Dry" },
  { number: "022", name: "Weepinbell", type: "Grass/Poison", specialty: "Grow, Litter", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Nature", f2: "Wooden stuff", f3: "Dirt", f4: "Colourful stuff", f5: "Pretty flowers", flavor: "Bitter" },
  { number: "023", name: "Victreebel", type: "Grass/Poison", specialty: "Grow, Chop", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Nature", f2: "Wooden stuff", f3: "Dirt", f4: "Colourful stuff", f5: "Pretty flowers", flavor: "Bitter" },
  { number: "024", name: "Slowpoke", type: "Water/Psychic", specialty: "Water, Yawn", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Water", f2: "Cleanliness", f3: "Strange stuff", f4: "Soft stuff", f5: "Healing", flavor: "Dry" },
  { number: "025", name: "Slowbro", type: "Water/Psychic", specialty: "Water, Trade", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Water", f2: "Cleanliness", f3: "Strange stuff", f4: "Group activities", f5: "Healing", flavor: "Dry" },
  { number: "026", name: "Slowking", type: "Water/Psychic", specialty: "Water, Teleport", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Water", f2: "Cleanliness", f3: "Strange stuff", f4: "Group activities", f5: "Healing", flavor: "Sour" },
  { number: "027", name: "Magnemite", type: "Electric/Steel", specialty: "Generate", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Electronics", f2: "Metal stuff", f3: "Shiny stuff", f4: "Hard stuff", f5: "Group activities", flavor: "Bitter" },
  { number: "030", name: "Onix", type: "Rock/Ground", specialty: "Crush, Bull", location: "Withered Wasteland", idealHabitat: "Dry", f1: "Stone stuff", f2: "Dirt", f3: "Blocky stuff", f4: "Slender objects", f5: "Exercise", flavor: "Dry" },
  { number: "032", name: "Cubone", type: "Ground", specialty: "Build", location: "Withered Wasteland", idealHabitat: "Dry", f1: "Dirt", f2: "Construction", f3: "Exercise", f4: "Slender objects", f5: "Group activities", flavor: "Bitter" },
  { number: "033", name: "Marowak", type: "Ground", specialty: "Build", location: "Withered Wasteland", idealHabitat: "Dry", f1: "Dirt", f2: "Construction", f3: "Exercise", f4: "Slender objects", f5: "Luxury", flavor: "Dry" },
  { number: "034", name: "Tyrogue", type: "Fighting", specialty: "Trade", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Exercise", f2: "Group activities", f3: "Fabric", f4: "Stone stuff", f5: "Round stuff", flavor: "Spicy" },
  { number: "035", name: "Hitmonlee", type: "Fighting", specialty: "Trade", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Exercise", f2: "Group activities", f3: "Fabric", f4: "Stone stuff", f5: "Round stuff", flavor: "Spicy" },
  { number: "036", name: "Hitmonchan", type: "Fighting", specialty: "Trade", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Exercise", f2: "Group activities", f3: "Fabric", f4: "Stone stuff", f5: "Round stuff", flavor: "Sweet" },
  { number: "037", name: "Hitmontop", type: "Fighting", specialty: "Trade", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Exercise", f2: "Group activities", f3: "Fabric", f4: "Stone stuff", f5: "Round stuff", flavor: "Sweet" },
  { number: "041", name: "Tangrowth", type: "Grass", specialty: "Appraise", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Nature", f2: "Complicated stuff", f3: "Letters/words", f4: "Strange stuff", f5: "Group activities", flavor: "Dry" },
  { number: "042", name: "Scyther", type: "Bug/Flying", specialty: "Chop", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Nature", f2: "Nice breezes", f3: "Wooden stuff", f4: "Sharp stuff", f5: "Exercise", flavor: "Spicy" },
  { number: "044", name: "Pinsir", type: "Bug", specialty: "Chop, Build", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Nature", f2: "Wooden stuff", f3: "Pretty flowers", f4: "Sharp stuff", f5: "Exercise", flavor: "Spicy" },
  { number: "045", name: "Magikarp", type: "Water", specialty: "???", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Group activities", f4: "Rides", f5: "Wobbly stuff", flavor: "Sweet" },
  { number: "048", name: "Hoothoot", type: "Normal/Flying", specialty: "Trade, Fly", location: "Withered Wasteland", idealHabitat: "Dark", f1: "Soft stuff", f2: "Nice breezes", f3: "Fabric", f4: "Wobbly stuff", f5: "Watching stuff", flavor: "Dry" },
  { number: "049", name: "Noctowl", type: "Normal/Flying", specialty: "Trade, Fly", location: "Withered Wasteland", idealHabitat: "Dark", f1: "Soft stuff", f2: "Nice breezes", f3: "Letters/words", f4: "Containers", f5: "Watching stuff", flavor: "Dry" },
  { number: "050", name: "Heracross", type: "Bug/Fighting", specialty: "Chop, Build", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Nature", f2: "Wooden stuff", f3: "Pretty flowers", f4: "Looks like food", f5: "Exercise", flavor: "Sweet" },
  { number: "051", name: "Volbeat", type: "Bug", specialty: "Hype", location: "Withered Wasteland", idealHabitat: "Dark", f1: "Nature", f2: "Wooden stuff", f3: "Shiny stuff", f4: "Cute stuff", f5: "Group activities", flavor: "Sweet" },
  { number: "052", name: "Illumise", type: "Bug", specialty: "Hype", location: "Withered Wasteland", idealHabitat: "Dark", f1: "Nature", f2: "Wooden stuff", f3: "Shiny stuff", f4: "Cute stuff", f5: "Group activities", flavor: "Sour" },
  { number: "053", name: "Gulpin", type: "Poison", specialty: "Storage", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Cute stuff", f2: "Looks like food", f3: "Round stuff", f4: "Containers", f5: "Colourful stuff", flavor: "Spicy" },
  { number: "055", name: "Cacnea", type: "Grass", specialty: "Grow", location: "Withered Wasteland", idealHabitat: "Dry", f1: "Nature", f2: "Pretty flowers", f3: "Cute stuff", f4: "Round stuff", f5: "Sharp stuff", flavor: "Spicy" },
  { number: "056", name: "Cacturne", type: "Grass/Dark", specialty: "Grow, Litter", location: "Withered Wasteland", idealHabitat: "Dry", f1: "Nature", f2: "Nice breezes", f3: "Luxury", f4: "Shiny stuff", f5: "Sharp stuff", flavor: "Dry" },
  { number: "057", name: "Combee", type: "Bug/Flying", specialty: "Litter", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Nature", f2: "Nice breezes", f3: "Wooden stuff", f4: "Gatherings", f5: "Group activities", flavor: "Sweet" },
  { number: "058", name: "Vespiquen", type: "Bug/Flying", specialty: "Honey, Search", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Nature", f2: "Nice breezes", f3: "Wooden stuff", f4: "Gatherings", f5: "Complicated stuff", flavor: "Sweet" },
  { number: "059.1", name: "Shellos (West)", type: "Water", specialty: "Water", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Cleanliness", f4: "Colourful stuff", f5: "Containers", flavor: "Sour" },
  { number: "059.2", name: "Shellos (East)", type: "Water", specialty: "Water", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Cleanliness", f4: "Colourful stuff", f5: "Containers", flavor: "Sour" },
  { number: "060.1", name: "Gastrodon (West)", type: "Water/Ground", specialty: "Water, Trade", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Cleanliness", f4: "Colourful stuff", f5: "Containers", flavor: "Dry" },
  { number: "060.2", name: "Gastrodon (East)", type: "Water/Ground", specialty: "Water, Trade", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Water", f2: "Ocean vibes", f3: "Cleanliness", f4: "Colourful stuff", f5: "Containers", flavor: "Dry" },
  { number: "061", name: "Drifloon", type: "Ghost/Flying", specialty: "Dream Isle", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Spooky stuff", f2: "Strange stuff", f3: "Nice breezes", f4: "Cute stuff", f5: "Round stuff", flavor: "Bitter" },
  { number: "063", name: "Drilbur", type: "Ground", specialty: "Search", location: "Withered Wasteland", idealHabitat: "Dark", f1: "Dirt", f2: "Stone stuff", f3: "Nature", f4: "Watching stuff", f5: "Sharp stuff", flavor: "Sour" },
  { number: "064", name: "Excadrill", type: "Ground/Steel", specialty: "Search, Chop", location: "Withered Wasteland", idealHabitat: "Dark", f1: "Dirt", f2: "Metal stuff", f3: "Exercise", f4: "Watching stuff", f5: "Sharp stuff", flavor: "Sour" },
  { number: "065", name: "Timburr", type: "Fighting", specialty: "Build", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Exercise", f2: "Construction", f3: "Wooden stuff", f4: "Slender objects", f5: "Blocky stuff", flavor: "Spicy" },
  { number: "066", name: "Gurdurr", type: "Fighting", specialty: "Build", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Exercise", f2: "Construction", f3: "Metal stuff", f4: "Slender objects", f5: "Group activities", flavor: "Spicy" },
  { number: "068", name: "Litwick", type: "Ghost/Fire", specialty: "Burn", location: "Withered Wasteland", idealHabitat: "Dark", f1: "Spooky stuff", f2: "Strange stuff", f3: "Fire", f4: "Wobbly stuff", f5: "Blocky stuff", flavor: "Bitter" },
  { number: "069", name: "Lampent", type: "Ghost/Fire", specialty: "Burn", location: "Withered Wasteland", idealHabitat: "Dark", f1: "Spooky stuff", f2: "Strange stuff", f3: "Fire", f4: "Wobbly stuff", f5: "Containers", flavor: "Bitter" },
  { number: "070", name: "Chandelure", type: "Ghost/Fire", specialty: "Burn", location: "Withered Wasteland", idealHabitat: "Dark", f1: "Spooky stuff", f2: "Strange stuff", f3: "Fire", f4: "Wobbly stuff", f5: "Watching stuff", flavor: "Dry" },
  { number: "071", name: "Axew", type: "Dragon", specialty: "Chop", location: "Withered Wasteland", idealHabitat: "Dark", f1: "Fire", f2: "Luxury", f3: "Dirt", f4: "Hard stuff", f5: "Sharp stuff", flavor: "Sweet" },
  { number: "072", name: "Fraxure", type: "Dragon", specialty: "Chop", location: "Withered Wasteland", idealHabitat: "Dark", f1: "Fire", f2: "Luxury", f3: "Dirt", f4: "Exercise", f5: "Sharp stuff", flavor: "Spicy" },
  { number: "073", name: "Haxorus", type: "Dragon", specialty: "Chop, Litter", location: "Withered Wasteland", idealHabitat: "Dark", f1: "Fire", f2: "Luxury", f3: "Dirt", f4: "Exercise", f5: "Sharp stuff", flavor: "Sour" },
  { number: "074", name: "Goomy", type: "Dragon", specialty: "Water", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Water", f2: "Luxury", f3: "Nature", f4: "Cleanliness", f5: "Healing", flavor: "Sweet" },
  { number: "075", name: "Sliggoo", type: "Dragon", specialty: "Water", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Water", f2: "Luxury", f3: "Soft stuff", f4: "Cleanliness", f5: "Healing", flavor: "Sweet" },
  { number: "076", name: "Goodra", type: "Dragon", specialty: "Water, Trade", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Water", f2: "Luxury", f3: "Exercise", f4: "Cleanliness", f5: "Healing", flavor: "Sour" },
  { number: "078", name: "Pichu", type: "Electric", specialty: "Generate", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Electronics", f2: "Glass stuff", f3: "Cute stuff", f4: "Pretty flowers", f5: "Fabric", flavor: "Sweet" },
  { number: "140", name: "Vikavolt", type: "Bug/Electric", specialty: "Generate, Chop", location: "Withered Wasteland", idealHabitat: "Humid", f1: "Nature", f2: "Electronics", f3: "Exercise", f4: "Glass stuff", f5: "Nice breezes", flavor: "Dry" },
  { number: "162", name: "Magby", type: "Fire", specialty: "Burn", location: "Withered Wasteland", idealHabitat: "Warm", f1: "Fire", f2: "Stone stuff", f3: "Watching stuff", f4: "Cute stuff", f5: "Wobbly stuff", flavor: "Sweet" },
  { number: "300", name: "Mew", type: "Psychic", specialty: "Teleport", location: "Withered Wasteland", idealHabitat: "Bright", f1: "Strange stuff", f2: "Watching stuff", f3: "Luxury", f4: "Complicated stuff", f5: "Play spaces", flavor: "Sweet" },
];

function normalizeName(name) {
  return name.toLowerCase().replace(/[^a-z0-9\s]/g, '').trim().replace(/\s+/g, '-').replace(/-+/g, '-');
}

export const POKEMON_DATA = RAW.map((p, i) => {
  const favouritesList = favs(p.f1, p.f2, p.f3, p.f4, p.f5);
  const specialtyList = sp(p.specialty);
  return {
    id: i + 1,
    number: p.number,
    name: p.name,
    type: p.type.trim(),
    specialty: specialtyList,
    location: p.location,
    idealHabitat: p.idealHabitat,
    favourites: favouritesList,
    favouritesNorm: favouritesList.map(normalizeFav),
    flavor: p.flavor.trim(),
    imageUrl: getImageUrl(p.name),
    dataSource: "sheet",
  };
});

export const ALL_TYPES = [...new Set(POKEMON_DATA.map(p => p.type))].sort();
export const ALL_SPECIALTIES = [...new Set(POKEMON_DATA.flatMap(p => p.specialty))].sort();
export const ALL_HABITATS = [...new Set(POKEMON_DATA.map(p => p.idealHabitat).filter(h => h && h !== 'N/a'))].sort();
export const ALL_FAVOURITES = [...new Set(POKEMON_DATA.flatMap(p => p.favourites))].sort();
export const ALL_LOCATIONS = [...new Set(POKEMON_DATA.map(p => p.location))].sort();
export const ALL_FLAVORS = [...new Set(POKEMON_DATA.map(p => p.flavor))].sort();

export const TOWNS = [
  { id: "withered-wasteland", name: "Withered Wasteland", color: "bg-amber-100 text-amber-800", icon: "🏜️" },
  { id: "bleak-beach", name: "Bleak Beach", color: "bg-cyan-100 text-cyan-800", icon: "🏖️" },
  { id: "rocky-ridges", name: "Rocky Ridges", color: "bg-stone-100 text-stone-800", icon: "⛰️" },
  { id: "sparkling-skylands", name: "Sparkling Skylands", color: "bg-violet-100 text-violet-800", icon: "✨" },
  { id: "palette-town", name: "Palette Town", color: "bg-rose-100 text-rose-800", icon: "🎨" },
];

export function getPokemonById(id) {
  return POKEMON_DATA.find(p => p.id === id);
}

export function searchPokemon(query) {
  const q = query.toLowerCase();
  return POKEMON_DATA.filter(p => p.name.toLowerCase().includes(q));
}

export const DATA_STATS = {
  totalPokemon: POKEMON_DATA.length,
  lastRefresh: new Date().toISOString(),
};